In [1]:
import os
import sys
sys.path.append('../utils')
sys.path.append('../dataset')
from spot import DailyDataset, PeriodDataset, TOTAL_STD, TOTAL_MEAN, get_daily_spot, reduce_hour_mean, get_loader
from tool import to_gpu

import numpy as np
import pandas as pd
from pandas.tseries.offsets import Day


import matplotlib.pyplot as plt

import types

%matplotlib inline

In [3]:
dataset = DailyDataset(N=2000, W=14)
loader = get_loader(dataset, batch_size=64, shuffle=True, num_workers=2)

Data build range: [window(2010-06-27 00:00:00) - 2010-07-11 00:00:00, 2015-12-31 00:00:00]


In [4]:
trainX, trainY = dataset.get_io('2012-01-01', '2015-12-31')
testX, testY = dataset.get_io('2012-01-01', '2016-08-30')

In [6]:
trainX.shape

torch.Size([1474, 24])

In [7]:
trainY.shape

torch.Size([1461, 24])

In [8]:
testX.shape

torch.Size([1717, 24])

In [9]:
testY.shape

torch.Size([1704, 24])

In [11]:
enumerate(loader)

In [2]:
spot=get_daily_spot(reduce_hour_mean())

In [34]:
end_date='2015-12-31'
dt = pd.to_datetime(end_date)

In [35]:
sliding = spot.loc[pd.to_datetime(dt) - Day(14+1):pd.to_datetime(dt)].values

In [36]:
sliding

array([[-5.97289152e-02, -1.19632258e-01, -6.71402142e-02,
         4.71354279e-02,  1.04492721e-01,  5.66675916e-02,
        -1.62165749e-01,  1.37935854e-02, -2.74194576e-03,
        -1.21579839e-01, -2.13337586e-01, -2.90764523e-01,
        -1.40444115e-01, -1.11460408e-01,  2.75681714e-02,
         6.53780509e-04,  1.13287850e-01,  5.16048500e-02,
        -4.30653860e-02, -4.36100837e-01, -4.06224636e-01,
        -2.78908823e-01, -3.86220121e-01, -3.66071197e-01],
       [ 1.41749177e-01, -4.58801711e-01, -3.64518360e-01,
        -2.66519332e-01, -2.25438653e-01, -2.57427077e-01,
        -3.65843384e-01, -3.61448364e-01, -2.26215463e-01,
        -2.99302873e-01, -3.45750044e-01, -3.97222380e-01,
        -2.78135476e-01, -3.80244501e-01, -3.09841647e-01,
        -2.39536260e-01, -1.58135694e-01, -5.74924577e-02,
        -2.22108145e-01, -5.77751373e-01, -5.43476088e-01,
        -3.66450615e-01, -5.85498671e-01, -3.43195955e-01],
       [-9.40417781e-02, -2.09373592e-01, -1.56441639e

In [42]:
p=sliding[13:15].reshape(24*2)
p

array([-0.53527   , -0.55030268, -0.55675837, -0.45040108, -0.46694842,
       -0.51037446, -0.57304029, -0.53873149, -0.78094008, -0.78408204,
       -0.44472946, -0.46188893, -0.22842582, -0.10486178, -0.12420026,
       -0.20742294, -0.1220632 ,  0.05776357,  0.24419486,  0.1195036 ,
       -0.06617537, -0.31762077, -0.37390268, -0.38850653, -0.35138825,
       -0.18781808, -0.09617418, -0.16534038, -0.29318456, -0.44614782,
       -0.48329895, -0.69137974, -0.72463179, -0.49638188, -0.57318274,
       -0.50060088, -0.53636176, -0.55972717, -0.61249869, -0.56066946,
       -0.49554551, -0.43185459, -0.31624856, -0.6309803 , -0.55227426,
       -0.38316714, -0.74914463, -0.3607923 ])

In [46]:
a=[]
a += [p]
a += [p]

In [47]:
a

[array([-0.53527   , -0.55030268, -0.55675837, -0.45040108, -0.46694842,
        -0.51037446, -0.57304029, -0.53873149, -0.78094008, -0.78408204,
        -0.44472946, -0.46188893, -0.22842582, -0.10486178, -0.12420026,
        -0.20742294, -0.1220632 ,  0.05776357,  0.24419486,  0.1195036 ,
        -0.06617537, -0.31762077, -0.37390268, -0.38850653, -0.35138825,
        -0.18781808, -0.09617418, -0.16534038, -0.29318456, -0.44614782,
        -0.48329895, -0.69137974, -0.72463179, -0.49638188, -0.57318274,
        -0.50060088, -0.53636176, -0.55972717, -0.61249869, -0.56066946,
        -0.49554551, -0.43185459, -0.31624856, -0.6309803 , -0.55227426,
        -0.38316714, -0.74914463, -0.3607923 ]),
 array([-0.53527   , -0.55030268, -0.55675837, -0.45040108, -0.46694842,
        -0.51037446, -0.57304029, -0.53873149, -0.78094008, -0.78408204,
        -0.44472946, -0.46188893, -0.22842582, -0.10486178, -0.12420026,
        -0.20742294, -0.1220632 ,  0.05776357,  0.24419486,  0.1195036 ,
  

In [49]:
b=np.array(a)

In [50]:
b.shape

(2, 48)

In [ ]:
tmp=[]
idx=0
for i in range(14):
    tmp += [sliding[i:i+2].reshape(24*2)]


In [20]:
def _sliding_window(date):
    _sliding = spot.loc[pd.to_datetime(date) - Day(15):
                             pd.to_datetime(date)].values
    x = _sliding[:15]
    y = _sliding[-14:]
    return x, y

In [26]:
end_date='2015-12-31'
dt = pd.to_datetime(end_date)
X_ = []
Y_ = []
dates_ = []
for _ in range(2):
    x, y = _sliding_window(dt)
    X_.append(x)
    Y_.append(y)
    dates_.append(dt)
    dt -= Day(1)

In [13]:
sliding.shape

(16, 24)

In [27]:
X_

[array([[-5.97289152e-02, -1.19632258e-01, -6.71402142e-02,
          4.71354279e-02,  1.04492721e-01,  5.66675916e-02,
         -1.62165749e-01,  1.37935854e-02, -2.74194576e-03,
         -1.21579839e-01, -2.13337586e-01, -2.90764523e-01,
         -1.40444115e-01, -1.11460408e-01,  2.75681714e-02,
          6.53780509e-04,  1.13287850e-01,  5.16048500e-02,
         -4.30653860e-02, -4.36100837e-01, -4.06224636e-01,
         -2.78908823e-01, -3.86220121e-01, -3.66071197e-01],
        [ 1.41749177e-01, -4.58801711e-01, -3.64518360e-01,
         -2.66519332e-01, -2.25438653e-01, -2.57427077e-01,
         -3.65843384e-01, -3.61448364e-01, -2.26215463e-01,
         -2.99302873e-01, -3.45750044e-01, -3.97222380e-01,
         -2.78135476e-01, -3.80244501e-01, -3.09841647e-01,
         -2.39536260e-01, -1.58135694e-01, -5.74924577e-02,
         -2.22108145e-01, -5.77751373e-01, -5.43476088e-01,
         -3.66450615e-01, -5.85498671e-01, -3.43195955e-01],
        [-9.40417781e-02, -2.09373592e

In [14]:
x = sliding[:15]
y = sliding[-14:]

In [28]:
Y_

[array([[-0.09404178, -0.20937359, -0.15644164, -0.06372151, -0.12293997,
         -0.15448849, -0.1700841 , -0.13885466, -0.11843788, -0.3265772 ,
         -0.39765925, -0.38930403, -0.40394931, -0.19416321, -0.18270809,
         -0.23029818, -0.18277057, -0.06453099, -0.19571364, -0.48537059,
         -0.39830628, -0.44475433, -0.57758032, -0.48088732],
        [ 0.03133214, -0.18825798, -0.1907545 , -0.176778  , -0.10974272,
         -0.2847014 , -0.56160267, -0.77100318, -0.83856809, -0.77528387,
         -0.56394466, -0.59298166, -0.55923701, -0.45414913, -0.50956011,
         -0.46696895, -0.33365918, -0.32935591, -0.31140957, -0.63273994,
         -0.85097213, -0.73905311, -0.82964789, -0.58470572],
        [-0.46576446, -0.58329582, -0.64869925, -0.57269565, -0.58572371,
         -0.59747635, -1.05649973, -1.30461219, -1.51734691, -1.40875211,
         -1.39097264, -1.34786465, -1.20634241, -1.10037471, -0.92263419,
         -0.93151233, -0.93061502, -0.70063868, -0.69412996, -

In [15]:
x

array([[-5.97289152e-02, -1.19632258e-01, -6.71402142e-02,
         4.71354279e-02,  1.04492721e-01,  5.66675916e-02,
        -1.62165749e-01,  1.37935854e-02, -2.74194576e-03,
        -1.21579839e-01, -2.13337586e-01, -2.90764523e-01,
        -1.40444115e-01, -1.11460408e-01,  2.75681714e-02,
         6.53780509e-04,  1.13287850e-01,  5.16048500e-02,
        -4.30653860e-02, -4.36100837e-01, -4.06224636e-01,
        -2.78908823e-01, -3.86220121e-01, -3.66071197e-01],
       [ 1.41749177e-01, -4.58801711e-01, -3.64518360e-01,
        -2.66519332e-01, -2.25438653e-01, -2.57427077e-01,
        -3.65843384e-01, -3.61448364e-01, -2.26215463e-01,
        -2.99302873e-01, -3.45750044e-01, -3.97222380e-01,
        -2.78135476e-01, -3.80244501e-01, -3.09841647e-01,
        -2.39536260e-01, -1.58135694e-01, -5.74924577e-02,
        -2.22108145e-01, -5.77751373e-01, -5.43476088e-01,
        -3.66450615e-01, -5.85498671e-01, -3.43195955e-01],
       [-9.40417781e-02, -2.09373592e-01, -1.56441639e

In [16]:
y

array([[-0.09404178, -0.20937359, -0.15644164, -0.06372151, -0.12293997,
        -0.15448849, -0.1700841 , -0.13885466, -0.11843788, -0.3265772 ,
        -0.39765925, -0.38930403, -0.40394931, -0.19416321, -0.18270809,
        -0.23029818, -0.18277057, -0.06453099, -0.19571364, -0.48537059,
        -0.39830628, -0.44475433, -0.57758032, -0.48088732],
       [ 0.03133214, -0.18825798, -0.1907545 , -0.176778  , -0.10974272,
        -0.2847014 , -0.56160267, -0.77100318, -0.83856809, -0.77528387,
        -0.56394466, -0.59298166, -0.55923701, -0.45414913, -0.50956011,
        -0.46696895, -0.33365918, -0.32935591, -0.31140957, -0.63273994,
        -0.85097213, -0.73905311, -0.82964789, -0.58470572],
       [-0.46576446, -0.58329582, -0.64869925, -0.57269565, -0.58572371,
        -0.59747635, -1.05649973, -1.30461219, -1.51734691, -1.40875211,
        -1.39097264, -1.34786465, -1.20634241, -1.10037471, -0.92263419,
        -0.93151233, -0.93061502, -0.70063868, -0.69412996, -0.81882123,
  

In [29]:
start_date = dates[-1]

for _ in range(15):
    dates_.append(dt)
    dt -= Day(1)

X = np.array(list(reversed(X_)))
Y = np.array(list(reversed(Y_)))
dates = np.array(list(reversed(dates_)))

In [31]:
X.shape

(2, 15, 24)

In [32]:
Y.shape

(2, 14, 24)

In [33]:
dates

array([Timestamp('2015-12-15 00:00:00'), Timestamp('2015-12-16 00:00:00'),
       Timestamp('2015-12-17 00:00:00'), Timestamp('2015-12-18 00:00:00'),
       Timestamp('2015-12-19 00:00:00'), Timestamp('2015-12-20 00:00:00'),
       Timestamp('2015-12-21 00:00:00'), Timestamp('2015-12-22 00:00:00'),
       Timestamp('2015-12-23 00:00:00'), Timestamp('2015-12-24 00:00:00'),
       Timestamp('2015-12-25 00:00:00'), Timestamp('2015-12-26 00:00:00'),
       Timestamp('2015-12-27 00:00:00'), Timestamp('2015-12-28 00:00:00'),
       Timestamp('2015-12-29 00:00:00'), Timestamp('2015-12-30 00:00:00'),
       Timestamp('2015-12-31 00:00:00')], dtype=object)

In [ ]:
def get_io(self, start_date, end_date):
    _sliding = self.spot.loc[pd.to_datetime(start_date) - Day(self.W):
                             pd.to_datetime(end_date)].values
    i_stream = _sliding[:-1]
    o_stream = _sliding[1:]
    return torch.from_numpy(i_stream).float(), torch.from_numpy(o_stream).float()

In [6]:
dataset = PeriodDataset(N=2000, W=14, P=7)
loader = get_loader(dataset, batch_size=64, shuffle=True, num_workers=2)

Data build range: [window(2010-06-21 00:00:00) - 2010-07-11 00:00:00, 2015-12-31 00:00:00]


In [7]:
trainX, trainY = dataset.get_io('2012-01-01', '2015-12-31')
testX, testY = dataset.get_io('2012-01-01', '2016-08-30')

(1481, 24)
(1724, 24)


In [8]:
trainX.shape

torch.Size([1473, 168])

In [9]:
trainY.shape

torch.Size([1473, 24])