In [1]:
# import __init__
import sys
sys.path.append('../utils')
sys.path.append('../dataset')
from data_loader import PeriodDataset
from basic_model import BasicRNN as Model
from tool import to_gpu

In [2]:
import torch
import torch.nn as nn
import types

In [3]:
PATH = '../runs/unemployment/'

In [6]:
loader = PeriodDataset.get_loader(batch_size=2, N=34, W=2)

Data build range: [window(1977-12-31 00:00:00) - 1979-12-31 00:00:00, 2012-12-31 00:00:00]


In [7]:
list(enumerate(loader))

[(0, [tensor([[[ 4.3000,  4.0000,  3.9000,  3.4000,  3.4000,  4.4000,  5.5000,
              6.0000,  5.0000,  4.3000,  4.4000,  4.4000],
            [ 5.0000,  4.2000,  4.0000,  3.5000,  3.9000,  5.8000,  6.4000,
              6.0000,  4.7000,  4.3000,  4.5000,  4.1000]],
   
           [[ 2.9000,  3.0000,  3.2000,  2.8000,  3.0000,  3.2000,  3.4000,
              4.0000,  3.9000,  3.7000,  3.2000,  3.2000],
            [ 3.8000,  3.8000,  3.3000,  3.1000,  3.3000,  3.9000,  4.0000,
              4.1000,  3.9000,  3.1000,  3.7000,  3.2000]]]),
   tensor([[[ 5.0000,  4.2000,  4.0000,  3.5000,  3.9000,  5.8000,  6.4000,
              6.0000,  4.7000,  4.3000,  4.5000,  4.1000],
            [ 4.2000,  3.9000,  3.7000,  3.7000,  4.2000,  5.2000,  5.7000,
              5.1000,  4.3000,  4.2000,  3.8000,  4.0000]],
   
           [[ 3.8000,  3.8000,  3.3000,  3.1000,  3.3000,  3.9000,  4.0000,
              4.1000,  3.9000,  3.1000,  3.7000,  3.2000],
            [ 3.6000,  3.6000,  3.2000,

In [23]:
testX, testY = loader.dataset.get_io('1977-01-01', '2012-12-31')

In [25]:
testX

tensor([[ 4.1000,  4.2000,  3.6000,  3.3000,  3.4000,  5.0000,  4.7000,
          5.4000,  4.9000,  4.1000,  4.2000,  3.8000],
        [ 4.1000,  3.3000,  3.2000,  3.1000,  3.4000,  4.9000,  4.9000,
          4.6000,  4.6000,  4.0000,  3.8000,  3.7000],
        [ 3.9000,  3.5000,  3.5000,  2.9000,  3.0000,  4.3000,  4.3000,
          4.7000,  3.8000,  4.1000,  3.6000,  3.4000],
        [ 3.8000,  3.7000,  3.6000,  3.5000,  3.6000,  4.2000,  4.8000,
          5.1000,  4.7000,  4.6000,  4.0000,  3.7000],
        [ 4.4000,  3.9000,  4.2000,  4.0000,  4.1000,  5.4000,  5.3000,
          5.5000,  5.2000,  4.8000,  5.0000,  4.4000],
        [ 4.8000,  4.7000,  4.4000,  4.5000,  4.4000,  5.4000,  5.3000,
          5.6000,  5.3000,  5.0000,  5.0000,  4.6000],
        [ 5.6000,  5.5000,  5.5000,  5.4000,  5.1000,  5.8000,  6.1000,
          5.8000,  5.3000,  5.0000,  4.6000,  4.4000],
        [ 5.0000,  4.4000,  4.2000,  4.1000,  4.3000,  4.6000,  5.0000,
          4.9000,  4.9000,  4.4000,  4.

In [18]:
testY

tensor([[ 5.0000,  4.2000,  4.0000,  3.5000,  3.9000,  5.8000,  6.4000,
          6.0000,  4.7000,  4.3000,  4.5000,  4.1000],
        [ 4.2000,  3.9000,  3.7000,  3.7000,  4.2000,  5.2000,  5.7000,
          5.1000,  4.3000,  4.2000,  3.8000,  4.0000],
        [ 4.2000,  3.8000,  3.6000,  3.3000,  3.8000,  5.2000,  5.3000,
          4.6000,  3.9000,  4.4000,  3.2000,  3.0000],
        [ 3.4000,  3.2000,  3.2000,  2.7000,  3.0000,  3.6000,  4.6000,
          3.9000,  3.0000,  2.7000,  3.0000,  2.8000],
        [ 2.8000,  2.4000,  2.4000,  2.4000,  2.3000,  3.3000,  4.2000,
          3.7000,  2.3000,  2.4000,  2.2000,  2.1000],
        [ 2.4000,  2.7000,  3.0000,  2.3000,  2.1000,  3.6000,  4.4000,
          3.7000,  2.5000,  2.2000,  2.1000,  1.9000],
        [ 2.2000,  2.1000,  1.8000,  1.8000,  2.2000,  3.3000,  4.1000,
          3.6000,  2.1000,  2.2000,  2.0000,  2.2000]])

In [11]:
model = to_gpu(Model(seq_dim=12, hidden_size=24))
model.load_state_dict(torch.load(PATH + 'snapshots49.pth'))

In [ ]:
model