In [1]:
import os
import sys
sys.path.append('../utils')
from spot import DailyDataset, TOTAL_STD, TOTAL_MEAN, get_daily_spot, reduce_hour_mean, get_loader
from tool import to_gpu

import numpy as np
import pandas as pd
from pandas.tseries.offsets import Day


import matplotlib.pyplot as plt

import types

%matplotlib inline

In [2]:
path = './seasonal'
TOTAL_STD = 22.732
TOTAL_MEAN = 38.99

In [3]:
day = pd.read_csv(os.path.join(path, 'day.csv'),
                   index_col='datetime', parse_dates=True)
day

0         1         2         3         4         5  \
datetime                                                                 
2011-06-17 -0.036482  0.012318 -0.125990 -0.150465 -0.234397 -0.131304   
2011-06-18 -0.006104 -0.113808 -0.171062 -0.210322 -0.235842 -0.134399   
2011-06-19 -0.259406 -0.202590 -0.356893 -0.289491 -0.331092 -0.311227   
2011-06-20 -0.191012 -0.253262 -0.284653 -0.168199 -0.207732 -0.156264   
2011-06-21 -0.081106 -0.160148 -0.232892 -0.324321 -0.279837 -0.204294   
2011-06-22 -0.094151 -0.118533 -0.264692 -0.388567 -0.345382 -0.238092   
2011-06-23 -0.131405 -0.221911 -0.392320 -0.388525 -0.327467 -0.192178   
2011-06-24 -0.165703 -0.142521 -0.314363 -0.314898 -0.285362 -0.144048   
2011-06-25 -0.134960 -0.104131 -0.246338 -0.304748 -0.230523 -0.167783   
2011-06-26 -0.046631  0.055394 -0.211328 -0.212663 -0.250563 -0.146775   
2011-06-27 -0.041068 -0.057184 -0.240269 -0.173272 -0.168989 -0.052391   
2011-06-28 -0.158124 -0.101132 -0.197008 -0.220177 -0.199455 -0.102272   
2011-06-29 -0.214944 -0.124685 -0.299421 -0.354214 -0.331997 -0.172081   
2011-06-30 -0.228904 -0.171057 -0.336852 -0.370136 -0.352324 -0.178265   
2011-07-01 -0.141551 -0.120792 -0.261668 -0.282575 -0.320298 -0.174655   
2011-07-02 -0.161053 -0.197403 -0.257987 -0.343216 -0.345938 -0.256196   
2011-07-03 -0.165929 -0.175279 -0.269907 -0.314017 -0.376119 -0.319414   
2011-07-04 -0.101087 -0.134735 -0.327652 -0.256474 -0.378808 -0.220603   
2011-07-05 -0.071597 -0.087464 -0.260134 -0.302773 -0.329829 -0.154040   
2011-07-06 -0.071618 -0.039557 -0.207317 -0.235650 -0.265449 -0.055203   
2011-07-07  0.022142  0.062484 -0.101064 -0.178535 -0.210461  0.007690   
2011-07-08  0.028819  0.039251 -0.068992 -0.168382 -0.159198 -0.011717   
2011-07-09 -0.034902 -0.008628 -0.119936 -0.237258 -0.213323 -0.082668   
2011-07-10 -0.001148  0.046383 -0.200179 -0.203295 -0.270155 -0.179366   
2011-07-11 -0.068866  0.028857 -0.060310 -0.056780 -0.153401 -0.126737   
2011-07-12 -0.047718  0.061145 -0.063204 -0.096859 -0.161993 -0.124964   
2011-07-13 -0.151384 -0.072792 -0.202861 -0.221599 -0.230292 -0.148011   
2011-07-14 -0.225522 -0.132677 -0.205323 -0.198858 -0.237248 -0.223066   
2011-07-15 -0.529178 -0.375776 -0.348782 -0.264052 -0.312944 -0.341121   
2011-07-16 -0.293846 -0.175280 -0.280620 -0.252568 -0.295775 -0.286798   
...              ...       ...       ...       ...       ...       ...   
2016-06-01 -0.529330 -0.353832 -0.336989 -0.348540 -0.442561 -0.290614   
2016-06-02 -0.525724 -0.330066 -0.300640 -0.333817 -0.416836 -0.265372   
2016-06-03 -0.565186 -0.370345 -0.342325 -0.346697 -0.419459 -0.300174   
2016-06-04 -0.527225 -0.319342 -0.316731 -0.348772 -0.443232 -0.313329   
2016-06-05 -0.551939 -0.327695 -0.364410 -0.383024 -0.446708 -0.318853   
2016-06-06 -0.516134 -0.302150 -0.366431 -0.356034 -0.420110 -0.263087   
2016-06-07 -0.529595 -0.329049 -0.386398 -0.375184 -0.449877 -0.291310   
2016-06-08 -0.535471 -0.345952 -0.377386 -0.369208 -0.457202 -0.293568   
2016-06-09 -0.527841 -0.312267 -0.331090 -0.330925 -0.421941 -0.263447   
2016-06-10 -0.519579 -0.305828 -0.304102 -0.325474 -0.375886 -0.237712   
2016-06-11 -0.566398 -0.340957 -0.359778 -0.359203 -0.428582 -0.339588   
2016-06-12 -0.577480 -0.355932 -0.384111 -0.390399 -0.445622 -0.317289   
2016-06-13 -0.571530 -0.359799 -0.399850 -0.388578 -0.440271 -0.305499   
2016-06-14 -0.557758 -0.380859 -0.427699 -0.440145 -0.490737 -0.349817   
2016-06-15 -0.493700 -0.316423 -0.318152 -0.314846 -0.417636 -0.278566   
2016-06-16 -0.527697 -0.292635 -0.288639 -0.328834 -0.422544 -0.259905   
2016-06-17 -0.542758 -0.317590 -0.309033 -0.344272 -0.400868 -0.268942   
2016-06-18 -0.532262 -0.298769 -0.309269 -0.330032 -0.395996 -0.282151   
2016-06-19 -0.579944 -0.345853 -0.374645 -0.395819 -0.425851 -0.303511   
2016-06-20 -0.541600 -0.317254 -0.366376 -0.345774 -0.405166 -0.245743   
2016-06-21 -0.539770 -0.342091 -0.381809 -0.384075 -0.417100 -0.292800   
2016-06-22 -0.493375 -0

In [4]:
week = pd.read_csv(os.path.join(path, 'week.csv'),
                   index_col='datetime', parse_dates=True)
week

0         1         2         3         4         5  \
datetime                                                                 
2011-06-17  0.015661  0.007380  0.142045  0.040514  0.089489  0.153715   
2011-06-18  0.011621  0.059583  0.183548  0.078545  0.101338  0.080095   
2011-06-19 -0.217096 -0.110150 -0.001721 -0.112699  0.053799  0.229197   
2011-06-20 -0.240654 -0.274188 -0.066168 -0.118321  0.004018  0.072683   
2011-06-21 -0.099073 -0.107331 -0.027099 -0.057879 -0.059537 -0.027135   
2011-06-22 -0.074264 -0.110928 -0.019120 -0.067842 -0.084512 -0.025823   
2011-06-23 -0.020434 -0.096924 -0.031268 -0.085718 -0.040464  0.040160   
2011-06-24 -0.064614 -0.056863  0.059105 -0.022968  0.074449  0.048370   
2011-06-25 -0.059491  0.042259  0.111137  0.030138  0.065485  0.004292   
2011-06-26 -0.065238  0.095421  0.127836  0.020440  0.038549 -0.045335   
2011-06-27 -0.088414 -0.176371 -0.033508 -0.079146 -0.052946 -0.051209   
2011-06-28 -0.093840 -0.157941 -0.084712 -0.093783 -0.114212 -0.085259   
2011-06-29 -0.103086 -0.092383  0.008962 -0.090278 -0.046784  0.034713   
2011-06-30 -0.011889 -0.048523  0.060136 -0.020775  0.038539  0.078030   
2011-07-01 -0.033967 -0.016503  0.106766  0.001044  0.081723  0.112675   
2011-07-02 -0.015743  0.094340  0.149310  0.063835  0.069002  0.017336   
2011-07-03 -0.056074  0.041913  0.052087 -0.032677  0.003008 -0.013409   
2011-07-04 -0.164569 -0.232437 -0.104906 -0.107510 -0.033955 -0.012113   
2011-07-05 -0.041025 -0.071024  0.034618 -0.013739 -0.016802  0.056052   
2011-07-06 -0.027521 -0.035038  0.088155  0.008292  0.000151  0.055166   
2011-07-07  0.040750 -0.001546  0.106619  0.022967  0.057021  0.128348   
2011-07-08  0.015349  0.041719  0.167141  0.056564  0.121608  0.142744   
2011-07-09  0.004950  0.121733  0.186943  0.079115  0.092456  0.060484   
2011-07-10 -0.044365  0.039892  0.089998 -0.026532  0.065546  0.099535   
2011-07-11 -0.152486 -0.182756 -0.043909 -0.077742 -0.001251  0.040608   
2011-07-12 -0.057683 -0.086767  0.031143 -0.023001 -0.023034  0.049447   
2011-07-13 -0.076197 -0.061046  0.033476 -0.044237 -0.007230  0.059681   
2011-07-14 -0.020576 -0.040933  0.044790 -0.023507  0.053624  0.140762   
2011-07-15 -0.144508 -0.137071 -0.029454 -0.075348  0.046869 -0.032380   
2011-07-16 -0.064695  0.012963  0.103297 -0.001895  0.108759  0.172258   
...              ...       ...       ...       ...       ...       ...   
2016-06-01 -0.100260 -0.036384  0.028942 -0.082260  0.015379  0.051070   
2016-06-02 -0.080478 -0.050717  0.025413 -0.070615  0.030746  0.102969   
2016-06-03 -0.091292 -0.051163  0.023385 -0.075146  0.035723  0.066573   
2016-06-04 -0.120945 -0.015592  0.046956 -0.068968  0.038958  0.082098   
2016-06-05 -0.152117 -0.039457  0.036450 -0.109013  0.036465  0.135192   
2016-06-06 -0.099729 -0.055313 -0.006391 -0.057855  0.013596  0.047083   
2016-06-07 -0.083004 -0.043024 -0.011344 -0.059080 -0.028014 -0.049145   
2016-06-08 -0.083270 -0.023463  0.022145 -0.074072 -0.003764 -0.001168   
2016-06-09 -0.086966 -0.042785  0.023971 -0.077643  0.029446  0.060806   
2016-06-10 -0.098838 -0.052467  0.025742 -0.077935  0.042171  0.072494   
2016-06-11 -0.124332 -0.018213  0.049092 -0.075140  0.048912  0.097412   
2016-06-12 -0.145162 -0.048588  0.029274 -0.111672  0.027836  0.146863   
2016-06-13 -0.091976 -0.060485 -0.009312 -0.064823  0.007323  0.042472   
2016-06-14 -0.078905 -0.051274  0.000461 -0.074694 -0.004407  0.037293   
2016-06-15 -0.083640 -0.038188  0.022185 -0.086455  0.013267  0.055829   
2016-06-16 -0.062055 -0.038936  0.020170 -0.062960  0.016672  0.035529   
2016-06-17 -0.084200 -0.031320  0.033094 -0.067042  0.036603  0.052241   
2016-06-18 -0.116437 -0.008683  0.045056 -0.074772  0.035961  0.078191   
2016-06-19 -0.162807 -0.059134  0.027760 -0.111290  0.031884  0.168567   
2016-06-20 -0.121469 -0.048388  0.001981 -0.068446  0.026121  0.062555   
2016-06-21 -0.080090 -0.023051  0.023151 -0.064374  0.006710  0.030507   
2016-06-22 -0.075740 -0

In [5]:
start_date = '2012-01-01'
end_date = '2016-06-30'
dt = pd.to_datetime(end_date)

In [6]:
t=week.loc[pd.to_datetime(start_date):pd.to_datetime(end_date)].values

In [7]:
t

array([[-0.11207492, -0.01224375,  0.02455396, ..., -0.3092294 ,
        -0.14997037, -0.14556114],
       [-0.10354   , -0.0922337 , -0.05790211, ..., -0.04224164,
        -0.03348773, -0.02534516],
       [-0.05742504, -0.08122887, -0.10049006, ..., -0.0150588 ,
        -0.0337239 , -0.0241482 ],
       ...,
       [-0.09038021, -0.0366924 , -0.00291857, ...,  0.03053609,
         0.03308648,  0.04456644],
       [-0.07676131, -0.01890462,  0.02687765, ..., -0.02057035,
         0.01543204,  0.03524301],
       [-0.06909911, -0.03846499,  0.02680144, ..., -0.12200463,
        -0.0390377 , -0.01389275]])

In [8]:
t.shape

(1643, 24)

In [9]:
spot = get_daily_spot(reduce_hour_mean())

In [10]:
s=spot.loc[pd.to_datetime(start_date):pd.to_datetime(end_date)].values

In [11]:
s

array([[-0.87485621, -1.20101696, -1.3069537 , ..., -0.4925009 ,
        -0.91187946, -0.98344276],
       [-0.36772969, -0.54546531, -0.6338497 , ..., -0.60133426,
        -0.37109994, -0.38538716],
       [-0.72022837, -0.72178064, -0.64141613, ..., -0.50745779,
        -0.62686275, -0.64326152],
       ...,
       [-0.44282207, -0.55201995, -0.55361039, ..., -0.53455615,
        -0.61137797, -0.50099511],
       [-0.37947525, -0.3166689 , -0.21356112, ..., -0.63309566,
        -0.56166831, -0.44820609],
       [-0.32052751, -0.23748537, -0.19728451, ..., -0.45537262,
        -0.37690674, -0.38881844]])

In [12]:
s.shape

(1643, 24)

In [13]:
p = np.concatenate((t,s), axis=-1)

In [14]:
p

array([[-0.11207492, -0.01224375,  0.02455396, ..., -0.4925009 ,
        -0.91187946, -0.98344276],
       [-0.10354   , -0.0922337 , -0.05790211, ..., -0.60133426,
        -0.37109994, -0.38538716],
       [-0.05742504, -0.08122887, -0.10049006, ..., -0.50745779,
        -0.62686275, -0.64326152],
       ...,
       [-0.09038021, -0.0366924 , -0.00291857, ..., -0.53455615,
        -0.61137797, -0.50099511],
       [-0.07676131, -0.01890462,  0.02687765, ..., -0.63309566,
        -0.56166831, -0.44820609],
       [-0.06909911, -0.03846499,  0.02680144, ..., -0.45537262,
        -0.37690674, -0.38881844]])

In [15]:
p[:,0:24]=s

In [16]:
p[0]

array([-0.87485621, -1.20101696, -1.3069537 , -1.21273237, -1.22340101,
       -1.03208887, -0.84001979, -0.81175228, -0.82459045, -0.7302771 ,
       -0.54287241, -0.27251091, -0.40464193, -0.44660119, -0.37655026,
       -0.46506768, -0.28862231, -0.26700001, -0.29048471, -0.47273251,
       -0.57485289, -0.4925009 , -0.91187946, -0.98344276, -0.87485621,
       -1.20101696, -1.3069537 , -1.21273237, -1.22340101, -1.03208887,
       -0.84001979, -0.81175228, -0.82459045, -0.7302771 , -0.54287241,
       -0.27251091, -0.40464193, -0.44660119, -0.37655026, -0.46506768,
       -0.28862231, -0.26700001, -0.29048471, -0.47273251, -0.57485289,
       -0.4925009 , -0.91187946, -0.98344276])

In [17]:
dataset = DailyDataset(N=2000, W=14)
loader = get_loader(dataset, batch_size=64, shuffle=True, num_workers=2)

Data build range: [window(2010-06-27 00:00:00) - 2010-07-11 00:00:00, 2015-12-31 00:00:00]


In [19]:
trainX, trainY = dataset.get_io('2012-01-01', '2015-12-31')
testX, testY = dataset.get_io('2012-01-01', '2016-08-30')

In [20]:
trainX.shape

torch.Size([1474, 24])

In [21]:
trainY.shape

torch.Size([1474, 24])

In [22]:
testX.shape

torch.Size([1716, 24])

In [23]:
testY.shape

torch.Size([1716, 24])

In [24]:
enumerate(loader)

In [25]:
spot=get_daily_spot(reduce_hour_mean())

In [26]:
end_date='2015-12-31'
dt = pd.to_datetime(end_date)

In [27]:
sliding = spot.loc[pd.to_datetime(dt) - Day(14+1):pd.to_datetime(dt)].values

In [28]:
sliding

array([[-0.36451836, -0.26651933, -0.22543865, -0.25742708, -0.36584338,
        -0.36144836, -0.22621546, -0.29930287, -0.34575004, -0.39722238,
        -0.27813548, -0.3802445 , -0.30984165, -0.23953626, -0.15813569,
        -0.05749246, -0.22210815, -0.57775137, -0.54347609, -0.36645061,
        -0.58549867, -0.34319596,  0.14174538, -0.45876389],
       [-0.15644164, -0.06372151, -0.12293997, -0.15448849, -0.1700841 ,
        -0.13885466, -0.11843788, -0.3265772 , -0.39765925, -0.38930403,
        -0.40394931, -0.19416321, -0.18270809, -0.23029818, -0.18277057,
        -0.06453099, -0.19571364, -0.48537059, -0.39830628, -0.44475433,
        -0.57758032, -0.48088732, -0.09404557, -0.20933577],
       [-0.1907545 , -0.176778  , -0.10974272, -0.2847014 , -0.56160267,
        -0.77100318, -0.83856809, -0.77528387, -0.56394466, -0.59298166,
        -0.55923701, -0.45414913, -0.50956011, -0.46696895, -0.33365918,
        -0.32935591, -0.31140957, -0.63273994, -0.85097213, -0.73905311,
  

In [29]:
p=sliding[13:15].reshape(24*2)
p

array([-0.09617418, -0.16534038, -0.29318456, -0.44614782, -0.48329895,
       -0.69137974, -0.72463179, -0.49638188, -0.57318274, -0.50060088,
       -0.53636176, -0.55972717, -0.61249869, -0.56066946, -0.49554551,
       -0.43185459, -0.31624856, -0.6309803 , -0.55227426, -0.38316714,
       -0.74914463, -0.3607923 , -0.35139204, -0.18778026, -0.79166951,
       -0.68795167, -0.68030404, -0.94324443, -1.11544747, -1.07717949,
       -1.1649802 , -1.19055749, -1.10855138, -1.05312595, -0.9313996 ,
       -0.76868371, -0.62437622, -0.55890983, -0.43087896, -0.33551463,
       -0.28237561, -0.56719357, -0.64641468, -0.73905311, -0.75574326,
       -0.53323643, -0.21194105, -0.83884484])

In [30]:
a=[]
a += [p]
a += [p]

In [31]:
a

[array([-0.09617418, -0.16534038, -0.29318456, -0.44614782, -0.48329895,
        -0.69137974, -0.72463179, -0.49638188, -0.57318274, -0.50060088,
        -0.53636176, -0.55972717, -0.61249869, -0.56066946, -0.49554551,
        -0.43185459, -0.31624856, -0.6309803 , -0.55227426, -0.38316714,
        -0.74914463, -0.3607923 , -0.35139204, -0.18778026, -0.79166951,
        -0.68795167, -0.68030404, -0.94324443, -1.11544747, -1.07717949,
        -1.1649802 , -1.19055749, -1.10855138, -1.05312595, -0.9313996 ,
        -0.76868371, -0.62437622, -0.55890983, -0.43087896, -0.33551463,
        -0.28237561, -0.56719357, -0.64641468, -0.73905311, -0.75574326,
        -0.53323643, -0.21194105, -0.83884484]),
 array([-0.09617418, -0.16534038, -0.29318456, -0.44614782, -0.48329895,
        -0.69137974, -0.72463179, -0.49638188, -0.57318274, -0.50060088,
        -0.53636176, -0.55972717, -0.61249869, -0.56066946, -0.49554551,
        -0.43185459, -0.31624856, -0.6309803 , -0.55227426, -0.38316714,
  

In [32]:
b=np.array(a)

In [33]:
b.shape

(2, 48)

In [34]:
tmp=[]
idx=0
for i in range(14):
    tmp += [sliding[i:i+2].reshape(24*2)]


In [35]:
def _sliding_window(date):
    _sliding = spot.loc[pd.to_datetime(date) - Day(15):
                             pd.to_datetime(date)].values
    x = _sliding[:15]
    y = _sliding[-14:]
    return x, y

In [36]:
end_date='2015-12-31'
dt = pd.to_datetime(end_date)
X_ = []
Y_ = []
dates_ = []
for _ in range(2):
    x, y = _sliding_window(dt)
    X_.append(x)
    Y_.append(y)
    dates_.append(dt)
    dt -= Day(1)

In [37]:
sliding.shape

(16, 24)

In [38]:
X_

[array([[-0.36451836, -0.26651933, -0.22543865, -0.25742708, -0.36584338,
         -0.36144836, -0.22621546, -0.29930287, -0.34575004, -0.39722238,
         -0.27813548, -0.3802445 , -0.30984165, -0.23953626, -0.15813569,
         -0.05749246, -0.22210815, -0.57775137, -0.54347609, -0.36645061,
         -0.58549867, -0.34319596,  0.14174538, -0.45876389],
        [-0.15644164, -0.06372151, -0.12293997, -0.15448849, -0.1700841 ,
         -0.13885466, -0.11843788, -0.3265772 , -0.39765925, -0.38930403,
         -0.40394931, -0.19416321, -0.18270809, -0.23029818, -0.18277057,
         -0.06453099, -0.19571364, -0.48537059, -0.39830628, -0.44475433,
         -0.57758032, -0.48088732, -0.09404557, -0.20933577],
        [-0.1907545 , -0.176778  , -0.10974272, -0.2847014 , -0.56160267,
         -0.77100318, -0.83856809, -0.77528387, -0.56394466, -0.59298166,
         -0.55923701, -0.45414913, -0.50956011, -0.46696895, -0.33365918,
         -0.32935591, -0.31140957, -0.63273994, -0.85097213, -

In [39]:
x = sliding[:15]
y = sliding[-14:]

In [40]:
Y_

[array([[-0.1907545 , -0.176778  , -0.10974272, -0.2847014 , -0.56160267,
         -0.77100318, -0.83856809, -0.77528387, -0.56394466, -0.59298166,
         -0.55923701, -0.45414913, -0.50956011, -0.46696895, -0.33365918,
         -0.32935591, -0.31140957, -0.63273994, -0.85097213, -0.73905311,
         -0.82964789, -0.58470572,  0.03132835, -0.18822017],
        [-0.64869925, -0.57269565, -0.58572371, -0.59747635, -1.05649973,
         -1.30461219, -1.51734691, -1.40875211, -1.39097264, -1.34786465,
         -1.20634241, -1.10037471, -0.92263419, -0.93151233, -0.93061502,
         -0.70063868, -0.69412996, -0.81882123, -0.7150404 , -0.55693099,
         -0.82040981, -0.56930892, -0.46576825, -0.583258  ],
        [-0.56643636, -0.38573454, -0.52765579, -0.5587644 , -0.62318986,
         -0.5290535 , -0.18398425, -0.16821014, -0.19134216, -0.34047418,
         -0.30101072, -0.36748715, -0.16027276, -0.39218451, -0.37193122,
         -0.22729714, -0.2454233 , -0.51836373, -0.51884121, -

In [41]:
x

array([[-0.36451836, -0.26651933, -0.22543865, -0.25742708, -0.36584338,
        -0.36144836, -0.22621546, -0.29930287, -0.34575004, -0.39722238,
        -0.27813548, -0.3802445 , -0.30984165, -0.23953626, -0.15813569,
        -0.05749246, -0.22210815, -0.57775137, -0.54347609, -0.36645061,
        -0.58549867, -0.34319596,  0.14174538, -0.45876389],
       [-0.15644164, -0.06372151, -0.12293997, -0.15448849, -0.1700841 ,
        -0.13885466, -0.11843788, -0.3265772 , -0.39765925, -0.38930403,
        -0.40394931, -0.19416321, -0.18270809, -0.23029818, -0.18277057,
        -0.06453099, -0.19571364, -0.48537059, -0.39830628, -0.44475433,
        -0.57758032, -0.48088732, -0.09404557, -0.20933577],
       [-0.1907545 , -0.176778  , -0.10974272, -0.2847014 , -0.56160267,
        -0.77100318, -0.83856809, -0.77528387, -0.56394466, -0.59298166,
        -0.55923701, -0.45414913, -0.50956011, -0.46696895, -0.33365918,
        -0.32935591, -0.31140957, -0.63273994, -0.85097213, -0.73905311,
  

In [42]:
y

array([[-0.1907545 , -0.176778  , -0.10974272, -0.2847014 , -0.56160267,
        -0.77100318, -0.83856809, -0.77528387, -0.56394466, -0.59298166,
        -0.55923701, -0.45414913, -0.50956011, -0.46696895, -0.33365918,
        -0.32935591, -0.31140957, -0.63273994, -0.85097213, -0.73905311,
        -0.82964789, -0.58470572,  0.03132835, -0.18822017],
       [-0.64869925, -0.57269565, -0.58572371, -0.59747635, -1.05649973,
        -1.30461219, -1.51734691, -1.40875211, -1.39097264, -1.34786465,
        -1.20634241, -1.10037471, -0.92263419, -0.93151233, -0.93061502,
        -0.70063868, -0.69412996, -0.81882123, -0.7150404 , -0.55693099,
        -0.82040981, -0.56930892, -0.46576825, -0.583258  ],
       [-0.56643636, -0.38573454, -0.52765579, -0.5587644 , -0.62318986,
        -0.5290535 , -0.18398425, -0.16821014, -0.19134216, -0.34047418,
        -0.30101072, -0.36748715, -0.16027276, -0.39218451, -0.37193122,
        -0.22729714, -0.2454233 , -0.51836373, -0.51884121, -0.4069222 ,
  

In [43]:
start_date = dates[-1]

for _ in range(15):
    dates_.append(dt)
    dt -= Day(1)

X = np.array(list(reversed(X_)))
Y = np.array(list(reversed(Y_)))
dates = np.array(list(reversed(dates_)))

NameError: name 'dates' is not defined

In [44]:
X.shape

NameError: name 'X' is not defined

In [32]:
Y.shape

(2, 14, 24)

In [33]:
dates

array([Timestamp('2015-12-15 00:00:00'), Timestamp('2015-12-16 00:00:00'),
       Timestamp('2015-12-17 00:00:00'), Timestamp('2015-12-18 00:00:00'),
       Timestamp('2015-12-19 00:00:00'), Timestamp('2015-12-20 00:00:00'),
       Timestamp('2015-12-21 00:00:00'), Timestamp('2015-12-22 00:00:00'),
       Timestamp('2015-12-23 00:00:00'), Timestamp('2015-12-24 00:00:00'),
       Timestamp('2015-12-25 00:00:00'), Timestamp('2015-12-26 00:00:00'),
       Timestamp('2015-12-27 00:00:00'), Timestamp('2015-12-28 00:00:00'),
       Timestamp('2015-12-29 00:00:00'), Timestamp('2015-12-30 00:00:00'),
       Timestamp('2015-12-31 00:00:00')], dtype=object)

In [ ]:
def get_io(self, start_date, end_date):
    _sliding = self.spot.loc[pd.to_datetime(start_date) - Day(self.W):
                             pd.to_datetime(end_date)].values
    i_stream = _sliding[:-1]
    o_stream = _sliding[1:]
    return torch.from_numpy(i_stream).float(), torch.from_numpy(o_stream).float()

In [6]:
dataset = PeriodDataset(N=2000, W=14, P=7)
loader = get_loader(dataset, batch_size=64, shuffle=True, num_workers=2)

Data build range: [window(2010-06-21 00:00:00) - 2010-07-11 00:00:00, 2015-12-31 00:00:00]


In [7]:
trainX, trainY = dataset.get_io('2012-01-01', '2015-12-31')
testX, testY = dataset.get_io('2012-01-01', '2016-08-30')

(1481, 24)
(1724, 24)


In [8]:
trainX.shape

torch.Size([1473, 168])

In [9]:
trainY.shape

torch.Size([1473, 24])

In [ ]:
# test self decomposion

In [6]:
dataset = DailyDataset(N=200, W=14)
loader = get_loader(dataset, batch_size=10, shuffle=True, num_workers=2)

Data build range: [window(2015-06-01 00:00:00) - 2015-06-15 00:00:00, 2015-12-31 00:00:00]


In [8]:
for _, (x, y, item) in enumerate(loader):
    print('x\' shape:', x.shape)
    print('y\' shape:', y.shape)
    break

x' shape: torch.Size([10, 14, 24])
y' shape: torch.Size([10, 14, 24])


Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f1c8413add8>>
Traceback (most recent call last):
  File "/home/xurenchao/install/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/xurenchao/install/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/xurenchao/install/anaconda3/lib/python3.5/multiprocessing/queues.py", line 337, in get
    return ForkingPickler.loads(res)
  File "/home/xurenchao/install/anaconda3/lib/python3.5/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/xurenchao/install/anaconda3/lib/python3.5/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/xurenchao/install/anaconda3/lib/python3.5/mu

In [9]:
x

tensor([[[-0.2783, -0.3519, -0.0495,  ...,  0.2362, -0.2938, -0.3413],
         [-0.1274, -0.0532,  0.0979,  ..., -0.2319, -0.2353, -0.1108],
         [ 0.0930,  0.1171,  0.1863,  ..., -0.0397, -0.1367, -0.0668],
         ...,
         [-0.0561,  0.0278, -0.0226,  ..., -0.2209, -0.1913, -0.1662],
         [-0.4358, -0.4557, -0.2439,  ...,  0.5067, -0.3822, -0.3950],
         [ 0.3605,  0.3348,  0.4683,  ..., -0.1664,  0.6050,  0.3212]],

        [[ 0.0129,  0.2103,  0.2228,  ..., -0.1034, -0.0391, -0.0778],
         [-0.0561,  0.0278, -0.0226,  ..., -0.2209, -0.1913, -0.1662],
         [-0.4358, -0.4557, -0.2439,  ...,  0.5067, -0.3822, -0.3950],
         ...,
         [-0.0575, -0.0774,  0.1529,  ...,  0.1152,  0.2258,  0.0225],
         [ 0.1893,  0.2064,  0.3742,  ..., -0.0960,  0.2157,  0.1479],
         [ 0.0969,  0.1188,  0.2316,  ...,  0.1640, -0.0184,  0.0317]],

        [[-0.5880, -0.4821, -0.3816,  ..., -0.4197, -0.6624, -0.5947],
         [-0.3126, -0.1834, -0.0552,  ..., -0

In [10]:
y

tensor([[[-0.1274, -0.0532,  0.0979,  ..., -0.2319, -0.2353, -0.1108],
         [ 0.0930,  0.1171,  0.1863,  ..., -0.0397, -0.1367, -0.0668],
         [-0.1749, -0.0778,  0.0187,  ..., -0.1052, -0.3356, -0.2784],
         ...,
         [-0.4358, -0.4557, -0.2439,  ...,  0.5067, -0.3822, -0.3950],
         [ 0.3605,  0.3348,  0.4683,  ..., -0.1664,  0.6050,  0.3212],
         [-0.0737, -0.0730,  0.0271,  ...,  0.0052, -0.4156, -0.2450]],

        [[-0.0561,  0.0278, -0.0226,  ..., -0.2209, -0.1913, -0.1662],
         [-0.4358, -0.4557, -0.2439,  ...,  0.5067, -0.3822, -0.3950],
         [ 0.3605,  0.3348,  0.4683,  ..., -0.1664,  0.6050,  0.3212],
         ...,
         [ 0.1893,  0.2064,  0.3742,  ..., -0.0960,  0.2157,  0.1479],
         [ 0.0969,  0.1188,  0.2316,  ...,  0.1640, -0.0184,  0.0317],
         [ 0.1906,  0.2640,  0.3258,  ...,  0.3035,  0.1725,  0.2046]],

        [[-0.3126, -0.1834, -0.0552,  ..., -0.3991, -0.4640, -0.3677],
         [-0.3038, -0.2749, -0.2219,  ..., -0