In [77]:
import os
import sys
sys.path.append('utils')
from dataset.spot import DailyDataset, PeriodDataset, TOTAL_STD, TOTAL_MEAN, get_daily_spot, reduce_hour_mean, get_loader
from tool import to_gpu

import numpy as np
import pandas as pd
from pandas.tseries.offsets import Day


import matplotlib.pyplot as plt

import types

%matplotlib inline

In [16]:
path = './dataset'
TOTAL_STD = 22.732
TOTAL_MEAN = 38.99

In [14]:
day = pd.read_csv(os.path.join(path, 'day.csv'),
                   index_col='datetime', parse_dates=True)
day

0         1         2         3         4         5  \
datetime                                                                 
2011-12-19  0.181913  0.302396  0.249803  0.348691  0.365587  0.170174   
2011-12-20 -0.035986  0.128604  0.133513  0.310839  0.286999  0.123465   
2011-12-21 -0.071354  0.120019  0.149453  0.274511  0.259724  0.135284   
2011-12-22 -0.225066 -0.030500 -0.033566  0.109074  0.073054 -0.064460   
2011-12-23 -0.327268 -0.140668 -0.179701 -0.074528 -0.107106 -0.157469   
2011-12-24 -0.327749 -0.106050 -0.114527  0.003408 -0.038485 -0.146648   
2011-12-25 -0.476646 -0.304683 -0.328810 -0.178170 -0.300469 -0.418161   
2011-12-26 -0.422575 -0.280685 -0.337203 -0.208285 -0.272215 -0.319567   
2011-12-27 -0.197544 -0.130735 -0.148077 -0.022647 -0.015186 -0.106483   
2011-12-28 -0.214948 -0.066383 -0.084359 -0.005683 -0.008299 -0.160208   
2011-12-29 -0.440074 -0.260591 -0.312158 -0.220624 -0.283680 -0.362697   
2011-12-30 -0.448046 -0.274291 -0.331619 -0.213821 -0.279474 -0.359253   
2011-12-31 -0.376028 -0.254327 -0.268902 -0.141911 -0.196962 -0.316391   
2012-01-01 -0.556696 -0.473324 -0.503288 -0.326472 -0.401377 -0.488302   
2012-01-02 -0.501583 -0.429937 -0.478142 -0.305332 -0.397286 -0.456960   
2012-01-03 -0.517689 -0.403179 -0.447806 -0.314480 -0.447329 -0.466434   
2012-01-04 -0.469901 -0.469056 -0.431060 -0.357092 -0.504337 -0.495177   
2012-01-05 -0.484534 -0.483335 -0.483065 -0.424376 -0.570197 -0.536114   
2012-01-06 -0.468460 -0.469902 -0.453024 -0.412019 -0.530493 -0.520209   
2012-01-07 -0.497988 -0.481513 -0.429282 -0.318702 -0.421084 -0.495761   
2012-01-08 -0.472404 -0.391271 -0.338146 -0.234570 -0.348018 -0.451323   
2012-01-09 -0.428907 -0.383542 -0.334600 -0.211731 -0.345909 -0.396902   
2012-01-10 -0.368350 -0.351856 -0.276885 -0.172091 -0.232436 -0.310911   
2012-01-11 -0.462773 -0.405521 -0.339906 -0.254505 -0.340888 -0.344106   
2012-01-12 -0.351890 -0.275738 -0.208114 -0.124340 -0.142545 -0.155913   
2012-01-13 -0.387500 -0.296138 -0.212453 -0.077944 -0.137627 -0.147088   
2012-01-14 -0.173667 -0.127287 -0.041475  0.095727  0.057879 -0.077240   
2012-01-15 -0.340269 -0.228857 -0.191328 -0.028536 -0.071280 -0.184369   
2012-01-16 -0.271661 -0.205372 -0.121192  0.043805  0.042108 -0.045592   
2012-01-17 -0.254929 -0.166135 -0.070906  0.091057  0.149046  0.045331   
...              ...       ...       ...       ...       ...       ...   
2016-06-01 -0.672469 -0.618044 -0.649785 -0.492820 -0.552067 -0.512319   
2016-06-02 -0.665689 -0.601948 -0.641395 -0.485955 -0.528998 -0.494873   
2016-06-03 -0.723181 -0.667283 -0.689797 -0.507731 -0.542940 -0.488239   
2016-06-04 -0.685327 -0.653163 -0.671043 -0.514718 -0.528951 -0.453630   
2016-06-05 -0.660014 -0.612219 -0.655830 -0.475399 -0.497300 -0.457501   
2016-06-06 -0.623434 -0.528097 -0.602456 -0.397473 -0.403135 -0.412938   
2016-06-07 -0.642607 -0.565606 -0.600787 -0.408408 -0.381436 -0.415726   
2016-06-08 -0.697007 -0.627327 -0.655245 -0.443340 -0.430117 -0.458184   
2016-06-09 -0.685964 -0.608365 -0.652651 -0.434939 -0.453235 -0.455291   
2016-06-10 -0.686744 -0.617846 -0.649692 -0.450192 -0.470330 -0.420491   
2016-06-11 -0.674524 -0.647073 -0.675183 -0.496539 -0.497815 -0.431938   
2016-06-12 -0.656995 -0.599978 -0.629603 -0.446771 -0.450774 -0.419996   
2016-06-13 -0.660418 -0.585801 -0.650591 -0.470551 -0.449599 -0.412053   
2016-06-14 -0.705086 -0.638647 -0.667885 -0.510984 -0.513487 -0.466669   
2016-06-15 -0.696458 -0.630020 -0.678953 -0.527515 -0.526048 -0.476094   
2016-06-16 -0.679435 -0.609914 -0.658969 -0.496959 -0.492484 -0.442571   
2016-06-17 -0.707768 -0.639775 -0.680895 -0.531030 -0.521958 -0.460799   
2016-06-18 -0.711322 -0.674005 -0.707142 -0.530765 -0.519004 -0.445433   
2016-06-19 -0.671388 -0.613832 -0.660631 -0.492177 -0.482369 -0.452163   
2016-06-20 -0.620399 -0.539596 -0.616264 -0.444513 -0.418021 -0.420730   
2016-06-21 -0.663322 -0.596753 -0.620033 -0.454287 -0.405997 -0.401323   
2016-06-22 -0.660282 -0

In [15]:
week = pd.read_csv(os.path.join(path, 'week.csv'),
                   index_col='datetime', parse_dates=True)
week

0         1         2         3         4         5  \
datetime                                                                 
2011-12-19  0.215659  0.006613 -0.091876  0.133539 -0.097635 -0.181059   
2011-12-20  0.110962  0.034912 -0.006505  0.107509 -0.047614 -0.146148   
2011-12-21  0.024160  0.001363 -0.025163  0.046211 -0.079200 -0.134092   
2011-12-22 -0.020941  0.005451  0.007475  0.036478 -0.033590 -0.111982   
2011-12-23  0.009259  0.042998  0.055038  0.070282  0.003399 -0.074607   
2011-12-24 -0.035310  0.096281  0.073234  0.036925 -0.000124 -0.035496   
2011-12-25 -0.072136  0.009878  0.009872 -0.041434  0.017832  0.048672   
2011-12-26 -0.099230 -0.084261 -0.073857 -0.045447 -0.009522 -0.069605   
2011-12-27  0.027632  0.029876 -0.029335  0.024478 -0.024166 -0.087511   
2011-12-28  0.058911  0.064035  0.001981  0.077594 -0.012435 -0.075558   
2011-12-29  0.041280  0.016564 -0.020820  0.029330 -0.019247 -0.058593   
2011-12-30 -0.006448 -0.001375 -0.024224  0.007160 -0.012159 -0.085543   
2011-12-31 -0.055657  0.069760  0.037852  0.025714  0.003267 -0.076613   
2012-01-01 -0.112075 -0.012244  0.024554 -0.096864  0.017511  0.124969   
2012-01-02 -0.103540 -0.092234 -0.057902 -0.069541 -0.012126 -0.007232   
2012-01-03 -0.057425 -0.081229 -0.100490 -0.077817 -0.070085 -0.060041   
2012-01-04 -0.084081 -0.086632 -0.077698 -0.081381 -0.064981 -0.059955   
2012-01-05 -0.028406 -0.069712 -0.061041 -0.049136 -0.037572 -0.047609   
2012-01-06 -0.016770 -0.077828 -0.062491 -0.053303 -0.019476 -0.066919   
2012-01-07 -0.008112 -0.000865  0.007102 -0.014528  0.000434 -0.072405   
2012-01-08 -0.058844  0.015051 -0.002099 -0.076516 -0.025425 -0.063953   
2012-01-09 -0.019472 -0.111585 -0.087223 -0.019184 -0.039980 -0.104152   
2012-01-10  0.019177 -0.130285 -0.159330 -0.053381 -0.150534 -0.191105   
2012-01-11 -0.089322 -0.100769 -0.089501 -0.064313 -0.125763 -0.201011   
2012-01-12 -0.046584 -0.084269 -0.068174 -0.045694 -0.090945 -0.157171   
2012-01-13 -0.076304 -0.074896 -0.043867 -0.048181 -0.039458 -0.124702   
2012-01-14 -0.035771  0.060165  0.050465  0.024532 -0.013817 -0.096818   
2012-01-15 -0.090018  0.077357  0.053871 -0.015467 -0.021308 -0.105996   
2012-01-16  0.027548 -0.131545 -0.113090 -0.006669 -0.131737 -0.206473   
2012-01-17 -0.038640 -0.066676 -0.047665 -0.012668 -0.092024 -0.200745   
...              ...       ...       ...       ...       ...       ...   
2016-06-01 -0.100260 -0.036384  0.028942 -0.082260  0.015379  0.051070   
2016-06-02 -0.080478 -0.050717  0.025413 -0.070615  0.030746  0.102969   
2016-06-03 -0.091292 -0.051163  0.023385 -0.075146  0.035723  0.066573   
2016-06-04 -0.120945 -0.015592  0.046956 -0.068968  0.038958  0.082098   
2016-06-05 -0.152117 -0.039457  0.036450 -0.109013  0.036465  0.135192   
2016-06-06 -0.099729 -0.055313 -0.006391 -0.057855  0.013596  0.047083   
2016-06-07 -0.083004 -0.043024 -0.011344 -0.059080 -0.028014 -0.049145   
2016-06-08 -0.083270 -0.023463  0.022145 -0.074072 -0.003764 -0.001168   
2016-06-09 -0.086966 -0.042785  0.023971 -0.077643  0.029446  0.060806   
2016-06-10 -0.098838 -0.052467  0.025742 -0.077935  0.042171  0.072494   
2016-06-11 -0.124332 -0.018213  0.049092 -0.075140  0.048912  0.097412   
2016-06-12 -0.145162 -0.048588  0.029274 -0.111672  0.027836  0.146863   
2016-06-13 -0.091976 -0.060485 -0.009312 -0.064823  0.007323  0.042472   
2016-06-14 -0.078905 -0.051274  0.000461 -0.074694 -0.004407  0.037293   
2016-06-15 -0.083640 -0.038188  0.022185 -0.086455  0.013267  0.055829   
2016-06-16 -0.062055 -0.038936  0.020170 -0.062960  0.016672  0.035529   
2016-06-17 -0.084200 -0.031320  0.033094 -0.067042  0.036603  0.052241   
2016-06-18 -0.116437 -0.008683  0.045056 -0.074772  0.035961  0.078191   
2016-06-19 -0.162807 -0.059134  0.027760 -0.111290  0.031884  0.168567   
2016-06-20 -0.121469 -0.048388  0.001981 -0.068446  0.026121  0.062555   
2016-06-21 -0.080090 -0.023051  0.023151 -0.064374  0.006710  0.030507   
2016-06-22 -0.075740 -0

In [39]:
start_date = '2012-01-01'
end_date = '2016-06-30'
dt = pd.to_datetime(end_date)

In [40]:
t=week.loc[pd.to_datetime(start_date):pd.to_datetime(end_date)].values

In [41]:
t

array([[-0.11207492, -0.01224375,  0.02455396, ..., -0.3092294 ,
        -0.14997037, -0.14556114],
       [-0.10354   , -0.0922337 , -0.05790211, ..., -0.04224164,
        -0.03348773, -0.02534516],
       [-0.05742504, -0.08122887, -0.10049006, ..., -0.0150588 ,
        -0.0337239 , -0.0241482 ],
       ...,
       [-0.09038021, -0.0366924 , -0.00291857, ...,  0.03053609,
         0.03308648,  0.04456644],
       [-0.07676131, -0.01890462,  0.02687765, ..., -0.02057035,
         0.01543204,  0.03524301],
       [-0.06909911, -0.03846499,  0.02680144, ..., -0.12200463,
        -0.0390377 , -0.01389275]])

In [42]:
t.shape

(1643, 24)

In [43]:
spot = get_daily_spot(reduce_hour_mean())

In [44]:
s=spot.loc[pd.to_datetime(start_date):pd.to_datetime(end_date)].values

In [45]:
s

array([[-0.28434619, -0.37011616, -0.31080553, ..., -0.84520303,
        -0.90152894, -0.74140113],
       [-0.91187567, -0.98348058, -0.87485621, ..., -0.47273251,
        -0.57485289, -0.4925009 ],
       [-0.37109615, -0.38542497, -0.36772969, ..., -0.45922732,
        -0.65236476, -0.60133426],
       ...,
       [-0.48775988, -0.40161361, -0.29105364, ..., -0.48610573,
        -0.42273253, -0.60582133],
       [-0.61137417, -0.50103293, -0.44282207, ..., -0.46762957,
        -0.37434259, -0.53455615],
       [-0.56166451, -0.44824391, -0.37947525, ..., -0.63787416,
        -0.48695917, -0.63309566]])

In [46]:
s.shape

(1643, 24)

In [64]:
p = np.concatenate((t,s), axis=-1)

In [65]:
p

array([[-0.11207492, -0.01224375,  0.02455396, ..., -0.84520303,
        -0.90152894, -0.74140113],
       [-0.10354   , -0.0922337 , -0.05790211, ..., -0.47273251,
        -0.57485289, -0.4925009 ],
       [-0.05742504, -0.08122887, -0.10049006, ..., -0.45922732,
        -0.65236476, -0.60133426],
       ...,
       [-0.09038021, -0.0366924 , -0.00291857, ..., -0.48610573,
        -0.42273253, -0.60582133],
       [-0.07676131, -0.01890462,  0.02687765, ..., -0.46762957,
        -0.37434259, -0.53455615],
       [-0.06909911, -0.03846499,  0.02680144, ..., -0.63787416,
        -0.48695917, -0.63309566]])

In [66]:
p[:,0:24]=s

In [68]:
p[0]

array([-0.28434619, -0.37011616, -0.31080553, -0.36417902, -0.42572899,
       -0.62149535, -0.97991166, -1.73466673, -2.01395961, -2.12171181,
       -1.73718063, -1.61928819, -1.3799303 , -1.04771767, -1.09754181,
       -1.28449491, -1.23067661, -1.32781623, -1.08516463, -1.17127592,
       -0.93024364, -0.84520303, -0.90152894, -0.74140113, -0.28434619,
       -0.37011616, -0.31080553, -0.36417902, -0.42572899, -0.62149535,
       -0.97991166, -1.73466673, -2.01395961, -2.12171181, -1.73718063,
       -1.61928819, -1.3799303 , -1.04771767, -1.09754181, -1.28449491,
       -1.23067661, -1.32781623, -1.08516463, -1.17127592, -0.93024364,
       -0.84520303, -0.90152894, -0.74140113])

In [54]:
p=10+True+False

In [55]:
p

11

In [70]:
import torch
a=torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [71]:
a.shape

torch.Size([3, 4])

In [76]:
a[-2:-1,:]

tensor([[ 5.,  6.,  7.,  8.]])

In [74]:
for i in range(1, 1):
    print(i)

In [79]:
pd.to_datetime(start_date)<pd.to_datetime(end_date)

True

In [3]:
dataset = DailyDataset(N=2000, W=14)
loader = get_loader(dataset, batch_size=64, shuffle=True, num_workers=2)

Data build range: [window(2010-06-27 00:00:00) - 2010-07-11 00:00:00, 2015-12-31 00:00:00]


In [4]:
trainX, trainY = dataset.get_io('2012-01-01', '2015-12-31')
testX, testY = dataset.get_io('2012-01-01', '2016-08-30')

In [6]:
trainX.shape

torch.Size([1474, 24])

In [7]:
trainY.shape

torch.Size([1461, 24])

In [8]:
testX.shape

torch.Size([1717, 24])

In [9]:
testY.shape

torch.Size([1704, 24])

In [11]:
enumerate(loader)

In [2]:
spot=get_daily_spot(reduce_hour_mean())

In [34]:
end_date='2015-12-31'
dt = pd.to_datetime(end_date)

In [35]:
sliding = spot.loc[pd.to_datetime(dt) - Day(14+1):pd.to_datetime(dt)].values

In [36]:
sliding

array([[-5.97289152e-02, -1.19632258e-01, -6.71402142e-02,
         4.71354279e-02,  1.04492721e-01,  5.66675916e-02,
        -1.62165749e-01,  1.37935854e-02, -2.74194576e-03,
        -1.21579839e-01, -2.13337586e-01, -2.90764523e-01,
        -1.40444115e-01, -1.11460408e-01,  2.75681714e-02,
         6.53780509e-04,  1.13287850e-01,  5.16048500e-02,
        -4.30653860e-02, -4.36100837e-01, -4.06224636e-01,
        -2.78908823e-01, -3.86220121e-01, -3.66071197e-01],
       [ 1.41749177e-01, -4.58801711e-01, -3.64518360e-01,
        -2.66519332e-01, -2.25438653e-01, -2.57427077e-01,
        -3.65843384e-01, -3.61448364e-01, -2.26215463e-01,
        -2.99302873e-01, -3.45750044e-01, -3.97222380e-01,
        -2.78135476e-01, -3.80244501e-01, -3.09841647e-01,
        -2.39536260e-01, -1.58135694e-01, -5.74924577e-02,
        -2.22108145e-01, -5.77751373e-01, -5.43476088e-01,
        -3.66450615e-01, -5.85498671e-01, -3.43195955e-01],
       [-9.40417781e-02, -2.09373592e-01, -1.56441639e

In [42]:
p=sliding[13:15].reshape(24*2)
p

array([-0.53527   , -0.55030268, -0.55675837, -0.45040108, -0.46694842,
       -0.51037446, -0.57304029, -0.53873149, -0.78094008, -0.78408204,
       -0.44472946, -0.46188893, -0.22842582, -0.10486178, -0.12420026,
       -0.20742294, -0.1220632 ,  0.05776357,  0.24419486,  0.1195036 ,
       -0.06617537, -0.31762077, -0.37390268, -0.38850653, -0.35138825,
       -0.18781808, -0.09617418, -0.16534038, -0.29318456, -0.44614782,
       -0.48329895, -0.69137974, -0.72463179, -0.49638188, -0.57318274,
       -0.50060088, -0.53636176, -0.55972717, -0.61249869, -0.56066946,
       -0.49554551, -0.43185459, -0.31624856, -0.6309803 , -0.55227426,
       -0.38316714, -0.74914463, -0.3607923 ])

In [46]:
a=[]
a += [p]
a += [p]

In [47]:
a

[array([-0.53527   , -0.55030268, -0.55675837, -0.45040108, -0.46694842,
        -0.51037446, -0.57304029, -0.53873149, -0.78094008, -0.78408204,
        -0.44472946, -0.46188893, -0.22842582, -0.10486178, -0.12420026,
        -0.20742294, -0.1220632 ,  0.05776357,  0.24419486,  0.1195036 ,
        -0.06617537, -0.31762077, -0.37390268, -0.38850653, -0.35138825,
        -0.18781808, -0.09617418, -0.16534038, -0.29318456, -0.44614782,
        -0.48329895, -0.69137974, -0.72463179, -0.49638188, -0.57318274,
        -0.50060088, -0.53636176, -0.55972717, -0.61249869, -0.56066946,
        -0.49554551, -0.43185459, -0.31624856, -0.6309803 , -0.55227426,
        -0.38316714, -0.74914463, -0.3607923 ]),
 array([-0.53527   , -0.55030268, -0.55675837, -0.45040108, -0.46694842,
        -0.51037446, -0.57304029, -0.53873149, -0.78094008, -0.78408204,
        -0.44472946, -0.46188893, -0.22842582, -0.10486178, -0.12420026,
        -0.20742294, -0.1220632 ,  0.05776357,  0.24419486,  0.1195036 ,
  

In [49]:
b=np.array(a)

In [50]:
b.shape

(2, 48)

In [ ]:
tmp=[]
idx=0
for i in range(14):
    tmp += [sliding[i:i+2].reshape(24*2)]


In [20]:
def _sliding_window(date):
    _sliding = spot.loc[pd.to_datetime(date) - Day(15):
                             pd.to_datetime(date)].values
    x = _sliding[:15]
    y = _sliding[-14:]
    return x, y

In [26]:
end_date='2015-12-31'
dt = pd.to_datetime(end_date)
X_ = []
Y_ = []
dates_ = []
for _ in range(2):
    x, y = _sliding_window(dt)
    X_.append(x)
    Y_.append(y)
    dates_.append(dt)
    dt -= Day(1)

In [13]:
sliding.shape

(16, 24)

In [27]:
X_

[array([[-5.97289152e-02, -1.19632258e-01, -6.71402142e-02,
          4.71354279e-02,  1.04492721e-01,  5.66675916e-02,
         -1.62165749e-01,  1.37935854e-02, -2.74194576e-03,
         -1.21579839e-01, -2.13337586e-01, -2.90764523e-01,
         -1.40444115e-01, -1.11460408e-01,  2.75681714e-02,
          6.53780509e-04,  1.13287850e-01,  5.16048500e-02,
         -4.30653860e-02, -4.36100837e-01, -4.06224636e-01,
         -2.78908823e-01, -3.86220121e-01, -3.66071197e-01],
        [ 1.41749177e-01, -4.58801711e-01, -3.64518360e-01,
         -2.66519332e-01, -2.25438653e-01, -2.57427077e-01,
         -3.65843384e-01, -3.61448364e-01, -2.26215463e-01,
         -2.99302873e-01, -3.45750044e-01, -3.97222380e-01,
         -2.78135476e-01, -3.80244501e-01, -3.09841647e-01,
         -2.39536260e-01, -1.58135694e-01, -5.74924577e-02,
         -2.22108145e-01, -5.77751373e-01, -5.43476088e-01,
         -3.66450615e-01, -5.85498671e-01, -3.43195955e-01],
        [-9.40417781e-02, -2.09373592e

In [14]:
x = sliding[:15]
y = sliding[-14:]

In [28]:
Y_

[array([[-0.09404178, -0.20937359, -0.15644164, -0.06372151, -0.12293997,
         -0.15448849, -0.1700841 , -0.13885466, -0.11843788, -0.3265772 ,
         -0.39765925, -0.38930403, -0.40394931, -0.19416321, -0.18270809,
         -0.23029818, -0.18277057, -0.06453099, -0.19571364, -0.48537059,
         -0.39830628, -0.44475433, -0.57758032, -0.48088732],
        [ 0.03133214, -0.18825798, -0.1907545 , -0.176778  , -0.10974272,
         -0.2847014 , -0.56160267, -0.77100318, -0.83856809, -0.77528387,
         -0.56394466, -0.59298166, -0.55923701, -0.45414913, -0.50956011,
         -0.46696895, -0.33365918, -0.32935591, -0.31140957, -0.63273994,
         -0.85097213, -0.73905311, -0.82964789, -0.58470572],
        [-0.46576446, -0.58329582, -0.64869925, -0.57269565, -0.58572371,
         -0.59747635, -1.05649973, -1.30461219, -1.51734691, -1.40875211,
         -1.39097264, -1.34786465, -1.20634241, -1.10037471, -0.92263419,
         -0.93151233, -0.93061502, -0.70063868, -0.69412996, -

In [15]:
x

array([[-5.97289152e-02, -1.19632258e-01, -6.71402142e-02,
         4.71354279e-02,  1.04492721e-01,  5.66675916e-02,
        -1.62165749e-01,  1.37935854e-02, -2.74194576e-03,
        -1.21579839e-01, -2.13337586e-01, -2.90764523e-01,
        -1.40444115e-01, -1.11460408e-01,  2.75681714e-02,
         6.53780509e-04,  1.13287850e-01,  5.16048500e-02,
        -4.30653860e-02, -4.36100837e-01, -4.06224636e-01,
        -2.78908823e-01, -3.86220121e-01, -3.66071197e-01],
       [ 1.41749177e-01, -4.58801711e-01, -3.64518360e-01,
        -2.66519332e-01, -2.25438653e-01, -2.57427077e-01,
        -3.65843384e-01, -3.61448364e-01, -2.26215463e-01,
        -2.99302873e-01, -3.45750044e-01, -3.97222380e-01,
        -2.78135476e-01, -3.80244501e-01, -3.09841647e-01,
        -2.39536260e-01, -1.58135694e-01, -5.74924577e-02,
        -2.22108145e-01, -5.77751373e-01, -5.43476088e-01,
        -3.66450615e-01, -5.85498671e-01, -3.43195955e-01],
       [-9.40417781e-02, -2.09373592e-01, -1.56441639e

In [16]:
y

array([[-0.09404178, -0.20937359, -0.15644164, -0.06372151, -0.12293997,
        -0.15448849, -0.1700841 , -0.13885466, -0.11843788, -0.3265772 ,
        -0.39765925, -0.38930403, -0.40394931, -0.19416321, -0.18270809,
        -0.23029818, -0.18277057, -0.06453099, -0.19571364, -0.48537059,
        -0.39830628, -0.44475433, -0.57758032, -0.48088732],
       [ 0.03133214, -0.18825798, -0.1907545 , -0.176778  , -0.10974272,
        -0.2847014 , -0.56160267, -0.77100318, -0.83856809, -0.77528387,
        -0.56394466, -0.59298166, -0.55923701, -0.45414913, -0.50956011,
        -0.46696895, -0.33365918, -0.32935591, -0.31140957, -0.63273994,
        -0.85097213, -0.73905311, -0.82964789, -0.58470572],
       [-0.46576446, -0.58329582, -0.64869925, -0.57269565, -0.58572371,
        -0.59747635, -1.05649973, -1.30461219, -1.51734691, -1.40875211,
        -1.39097264, -1.34786465, -1.20634241, -1.10037471, -0.92263419,
        -0.93151233, -0.93061502, -0.70063868, -0.69412996, -0.81882123,
  

In [29]:
start_date = dates[-1]

for _ in range(15):
    dates_.append(dt)
    dt -= Day(1)

X = np.array(list(reversed(X_)))
Y = np.array(list(reversed(Y_)))
dates = np.array(list(reversed(dates_)))

In [31]:
X.shape

(2, 15, 24)

In [32]:
Y.shape

(2, 14, 24)

In [33]:
dates

array([Timestamp('2015-12-15 00:00:00'), Timestamp('2015-12-16 00:00:00'),
       Timestamp('2015-12-17 00:00:00'), Timestamp('2015-12-18 00:00:00'),
       Timestamp('2015-12-19 00:00:00'), Timestamp('2015-12-20 00:00:00'),
       Timestamp('2015-12-21 00:00:00'), Timestamp('2015-12-22 00:00:00'),
       Timestamp('2015-12-23 00:00:00'), Timestamp('2015-12-24 00:00:00'),
       Timestamp('2015-12-25 00:00:00'), Timestamp('2015-12-26 00:00:00'),
       Timestamp('2015-12-27 00:00:00'), Timestamp('2015-12-28 00:00:00'),
       Timestamp('2015-12-29 00:00:00'), Timestamp('2015-12-30 00:00:00'),
       Timestamp('2015-12-31 00:00:00')], dtype=object)

In [ ]:
def get_io(self, start_date, end_date):
    _sliding = self.spot.loc[pd.to_datetime(start_date) - Day(self.W):
                             pd.to_datetime(end_date)].values
    i_stream = _sliding[:-1]
    o_stream = _sliding[1:]
    return torch.from_numpy(i_stream).float(), torch.from_numpy(o_stream).float()

In [6]:
dataset = PeriodDataset(N=2000, W=14, P=7)
loader = get_loader(dataset, batch_size=64, shuffle=True, num_workers=2)

Data build range: [window(2010-06-21 00:00:00) - 2010-07-11 00:00:00, 2015-12-31 00:00:00]


In [7]:
trainX, trainY = dataset.get_io('2012-01-01', '2015-12-31')
testX, testY = dataset.get_io('2012-01-01', '2016-08-30')

(1481, 24)
(1724, 24)


In [8]:
trainX.shape

torch.Size([1473, 168])

In [9]:
trainY.shape

torch.Size([1473, 24])