In [1]:
from data_loader import SPOT, PeriodDataset, get_year_spot

In [2]:
import sys;
sys.path.append('/home/xurenchao/work/rnn/Time-Series-Decomposition/dataset0/');
from spot import DailyDataset,SPOT as S, get_daily_spot

/home/xurenchao/install/anaconda3/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [3]:
import types
import pandas as pd
import torch
import torch.nn as nn
from torch.autograd import Variable

In [4]:
SPOT

Month
1977-01-01    4.1
1977-02-01    4.2
1977-03-01    3.6
1977-04-01    3.3
1977-05-01    3.4
1977-06-01    5.0
1977-07-01    4.7
1977-08-01    5.4
1977-09-01    4.9
1977-10-01    4.1
1977-11-01    4.2
1977-12-01    3.8
1978-01-01    4.1
1978-02-01    3.3
1978-03-01    3.2
1978-04-01    3.1
1978-05-01    3.4
1978-06-01    4.9
1978-07-01    4.9
1978-08-01    4.6
1978-09-01    4.6
1978-10-01    4.0
1978-11-01    3.8
1978-12-01    3.7
1979-01-01    3.9
1979-02-01    3.5
1979-03-01    3.5
1979-04-01    2.9
1979-05-01    3.0
1979-06-01    4.3
             ... 
2015-07-01    4.2
2015-08-01    3.7
2015-09-01    2.3
2015-10-01    2.4
2015-11-01    2.2
2015-12-01    2.1
2016-01-01    2.4
2016-02-01    2.7
2016-03-01    3.0
2016-04-01    2.3
2016-05-01    2.1
2016-06-01    3.6
2016-07-01    4.4
2016-08-01    3.7
2016-09-01    2.5
2016-10-01    2.2
2016-11-01    2.1
2016-12-01    1.9
2017-01-01    2.2
2017-02-01    2.1
2017-03-01    1.8
2017-04-01    1.8
2017-05-01    2.2
2017-06-01    3.3
2017

In [5]:
type(SPOT)

pandas.core.series.Series

In [6]:
from pandas.tseries.offsets import MonthOffset

In [7]:
get_daily_spot(S)

hour0   hour1   hour2   hour3   hour4   hour5   hour6   hour7  \
date                                                                         
2005-04-22  33.171  32.054  30.861  29.630  29.509  31.058  36.065  48.054   
2005-04-23  34.678  33.476  33.022  32.158  32.677  33.107  32.184  35.465   
2005-04-24  32.608  31.223  29.690  25.056  23.082  27.061  14.199  20.016   
2005-04-25  29.003  28.324  27.047  23.186  18.976  32.009  30.958  37.292   
2005-04-26  33.664  32.002  30.328  27.296  27.006  33.108  33.251  45.393   
2005-04-27  33.844  32.495  31.360  27.070  27.006  33.010  35.898  48.019   
2005-04-28  33.274  32.001  30.299  28.981  27.075  32.099  33.610  42.068   
2005-04-29  32.805  31.572  29.579  24.081  18.873  30.083  33.006  38.084   
2005-04-30  32.037  30.551  29.089  27.031  27.038  23.026  27.416  30.136   
2005-05-01  25.074  23.100  23.023  10.750   8.214  11.453   7.760   8.221   
2005-05-02  17.018   9.008   8.259   8.245   8.243  10.944  27.097  34.691   
2005-05-03  29.048  23.242  21.046  15.051   9.062  21.811  33.100  36.067   
2005-05-04  29.082  27.569  24.004  18.987  12.032  23.184  34.016  40.751   
2005-05-05  29.093  27.248  25.083  20.058  17.766  12.061  12.085  17.247   
2005-05-06  25.099  20.003  15.756  14.369  12.028  17.762  18.048  33.004   
2005-05-07  29.656  29.072  27.164  23.188  23.076  22.709  27.098  31.545   
2005-05-08  23.443  18.073  15.005  14.995  12.081  15.050   8.255  13.132   
2005-05-09  33.205  32.689  32.306  29.064  28.100  32.012  35.781  45.716   
2005-05-10  33.187  32.241  31.733  29.034  25.933  33.189  36.085  46.981   
2005-05-11  32.258  32.011  29.051  18.890  21.003  30.090  33.205  49.798   
2005-05-12  33.195  32.771  31.176  31.696  32.054  33.077  33.276  45.903   
2005-05-13  33.251  32.066  31.143  29.823  27.015  33.105  36.597  47.795   
2005-05-14  35.485  36.270  34.294  33.005  33.035  33.074  29.798  33.115   
2005-05-15  29.095  24.043  24.650  23.111  21.866  21.814  20.021  17.609   
2005-05-16  25.992  11.504   8.258   8.245  10.935  14.983   8.254  25.999   
2005-05-17  34.956  33.109  29.792  28.237  27.623  32.003  33.185  48.025   
2005-05-18  36.242  34.317  33.108  31.232  30.004  34.005  37.997  45.072   
2005-05-19  34.853  33.143  32.502  30.082  29.027  33.101  37.243  45.930   
2005-05-20  33.003  30.713  29.524  27.062  24.061  31.812  33.208  45.030   
2005-05-21  33.492  32.748  31.580  27.541  27.086  28.084  27.647  33.200   
...            ...     ...     ...     ...     ...     ...     ...     ...   
2016-08-01  25.140  24.030  22.850  22.140  22.420  23.930  29.060  32.170   
2016-08-02  27.560  25.790  25.350  24.700  24.270  25.900  30.430  34.870   
2016-08-03  26.030  24.530  23.740  22.690  22.480  23.660  27.060  31.820   
2016-08-04  24.520  22.430  20.050  19.420  19.830  22.420  25.490  30.010   
2016-08-05  28.130  26.830  25.120  23.950  24.070  26.240  30.450  34.010   
2016-08-06  29.580  26.680  25.340  23.770  22.400  22.010  22.970  25.020   
2016-08-07  24.600  20.050  17.990  12.860  12.380  12.350  12.510  11.930   
2016-08-08  20.620  16.440  12.910   8.160   8.120   8.940  17.850  23.710   
2016-08-09  23.880  23.060  22.600  20.320  19.940  22.970  28.330  32.860   
2016-08-10  23.350  23.110  22.000  19.990  20.190  23.180  23.090  31.050   
2016-08-11  24.230  23.010  22.720  20.490  18.570  22.770  24.240  25.550   
2016-08-12  24.070  22.970  21.050  19.900  20.050  22.980  27.930  32.550   
2016-08-13  21.700  19.970  18.090  16.890  16.100  14.460  16.080  18.050   
2016-08-14  23.440  21.180  19.700  19.030  18.050  18.080  18.060  19.250   
2016-08-15  25.150  22.940  21.610  21.010  21.500  23.290  27.210  25.940   
2016-08-16  26.260  23.990  22.940  22.030  22.100  24.100  28.710  33.630   
2016-08-17  30.800  24.010  23.510  21.900  22.560  25.050  29.740  34.750   
2016-08-18  27.030  24.120  24.200  21.830  22.490  25.050  30.260  33.790   
2016-08-19  31.460  26.620  25.000 

In [8]:
SPOT.index.year

Int64Index([1977, 1977, 1977, 1977, 1977, 1977, 1977, 1977, 1977, 1977,
            ...
            2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017],
           dtype='int64', name='Month', length=492)

In [9]:
MonthOffset(12)

<12 * MonthOffsets>

In [10]:
ts = pd.Timestamp('2015-07-15')
ts

Timestamp('2015-07-15 00:00:00')

In [11]:
ts1 = ts + pd.tseries.offsets.MonthOffset(months=1)
print(ts1)

2015-08-15 00:00:00


In [12]:
pd.to_datetime('2015-07-15')

Timestamp('2015-07-15 00:00:00')

In [14]:
daily=DailyDataset.get_loader(batch_size=64,N=2000, W=14)

Data build range: [window(2010-06-27 00:00:00) - 2010-07-11 00:00:00, 2015-12-31 00:00:00]


In [23]:
trainX, trainY = daily.dataset.get_io('2012-01-01', '2015-12-31')

In [24]:
trainX


 8.2914e-01  6.2719e-01  6.9204e-01  ...   6.4834e-01  5.0663e-01  6.3300e-01
 7.2972e-01  7.3666e-01  6.6974e-01  ...   5.2421e-01  2.0797e-01  3.3662e-01
 4.0984e-01  2.2321e-01  3.9767e-01  ...   3.3105e-01  1.9216e-01  3.6137e-01
                ...                   ⋱                   ...                
-4.6728e-01 -3.2482e-01 -4.6274e-01  ...  -6.8053e-01 -7.0820e-01 -6.6629e-01
-5.4369e-01 -5.5896e-01 -5.6552e-01  ...  -3.2262e-01 -3.7978e-01 -3.9462e-01
-3.5691e-01 -1.9077e-01 -9.7687e-02  ...  -3.8919e-01 -7.6093e-01 -3.6647e-01
[torch.FloatTensor of size 1474x24]

In [25]:
trainY


 7.2972e-01  7.3666e-01  6.6974e-01  ...   5.2421e-01  2.0797e-01  3.3662e-01
 4.0984e-01  2.2321e-01  3.9767e-01  ...   3.3105e-01  1.9216e-01  3.6137e-01
 4.3522e-01  3.8072e-01  4.0625e-01  ...   4.1572e-01  2.7442e-01  2.6311e-01
                ...                   ⋱                   ...                
-5.4369e-01 -5.5896e-01 -5.6552e-01  ...  -3.2262e-01 -3.7978e-01 -3.9462e-01
-3.5691e-01 -1.9077e-01 -9.7687e-02  ...  -3.8919e-01 -7.6093e-01 -3.6647e-01
-2.1527e-01 -8.5208e-01 -8.0412e-01  ...  -7.5068e-01 -7.6763e-01 -5.4162e-01
[torch.FloatTensor of size 1474x24]

In [28]:
trainX.split(1, dim=0)

(
 
 Columns 0 to 9 
  0.8291  0.6272  0.6920  0.7101  0.6296  0.3082  0.0141 -0.2086 -0.4090 -0.4354
 
 Columns 10 to 19 
 -0.2783 -0.0700  0.1627  0.4351  0.2490  0.2268  0.2236  0.1365  0.3803  0.4799
 
 Columns 20 to 23 
  0.5603  0.6483  0.5066  0.6330
 [torch.FloatTensor of size 1x24], 
 
 Columns 0 to 9 
  0.7297  0.7367  0.6697  0.5816  0.5336  0.4012  0.2831  0.2653  0.5578  0.4879
 
 Columns 10 to 19 
  0.4653  0.4413  0.5932  0.7153  0.6843  0.7207  0.7577  0.7851  0.8242  0.8270
 
 Columns 20 to 23 
  0.5592  0.5242  0.2080  0.3366
 [torch.FloatTensor of size 1x24], 
 
 Columns 0 to 9 
  0.4098  0.2232  0.3977  0.4330  0.3680  0.3261  0.2587  0.0744  0.1533  0.0190
 
 Columns 10 to 19 
  0.0989  0.1851  0.3275  0.3385  0.4830  0.4915  0.4780  0.4778  0.6588  0.5295
 
 Columns 20 to 23 
  0.4325  0.3310  0.1922  0.3614
 [torch.FloatTensor of size 1x24], 
 
 Columns 0 to 9 
  0.4352  0.3807  0.4062  0.4880  0.4627  0.4475  0.2862  0.1532  0.1511  0.2243
 
 Columns 10 to 19 
 

In [15]:
daily.X.shape, daily.Y.shape

AttributeError: 'DataLoader' object has no attribute 'X'

In [15]:
daily.X


array([[[ 0.25421101,  0.2189687 ,  0.28859556, ...,  0.45303148,
          0.23022539,  0.17575825],
        [ 0.06310287,  0.15878103,  0.19869386, ...,  0.31777679,
          0.26324594,  0.1046233 ],
        [ 0.19219134,  0.18639497,  0.19945347, ...,  0.64150333,
          0.51833978,  0.47803707],
        ...,
        [ 0.3280716 ,  0.28523322, -0.12431775, ...,  0.06210208,
          0.33755336,  0.33871624],
        [ 0.27060958,  0.02433063, -0.14013545, ...,  0.2431566 ,
          0.23415747, -0.09412558],
        [-0.11191947, -0.1577069 , -0.10152955, ...,  0.64838448,
          0.43554264,  0.30757237]],

       [[ 0.06310287,  0.15878103,  0.19869386, ...,  0.31777679,
          0.26324594,  0.1046233 ],
        [ 0.19219134,  0.18639497,  0.19945347, ...,  0.64150333,
          0.51833978,  0.47803707],
        [ 0.59840225,  0.38474171,  0.28108886, ...,  0.3825221 ,
          0.30140501,  0.43518631],
        ...,
        [ 0.27060958,  0.02433063, -0.14013545, ...,  

In [16]:
daily.X[14]

array([[ 0.15532807,  0.30922786,  0.26594141,  0.38746571,  0.48504596,
         0.49996281,  0.90177159,  0.97594083,  0.85914522,  0.6723971 ,
         0.62736416,  0.53057823,  0.54103773,  0.5976891 ,  0.62371223,
         0.6694755 ,  0.72141463,  0.70751034,  0.58449677,  0.44073082,
         0.47000454,  0.51013604,  0.43527454,  0.15484672],
       [ 0.04174452,  0.216109  ,  0.281491  ,  0.33576776,  0.36252585,
         0.5416965 ,  0.48327293,  1.11749579,  0.77210322,  0.6159181 ,
         0.48455809,  0.49067654,  0.46266418,  0.42061135,  0.3761251 ,
         0.33145048,  0.34339854,  0.6480376 ,  0.69294181,  0.59283091,
         0.58318595,  0.64722273,  0.20855425,  0.22946691],
       [ 0.00514934,  0.14886146,  0.23528904,  0.26802871,  0.4077448 ,
         0.52288506,  0.90409509,  0.9628041 ,  0.68363137,  0.53213794,
         0.475979  ,  0.31230299,  0.34858911,  0.37315827,  0.4540965 ,
         0.36281777,  0.39491776,  0.70116539,  0.73677559,  0.76186576,
  

In [17]:
daily.X[13]

array([[-0.11191947, -0.1577069 , -0.10152955, -0.2697729 , -0.25431955,
         0.3056822 ,  0.7776429 ,  0.78322412,  0.63211216,  0.50957315,
         0.44684584,  0.39737895,  0.35189564,  0.51028963,  0.45043251,
         0.58122707,  0.72454242,  0.84079899,  0.77377291,  0.68031974,
         0.69480347,  0.64838448,  0.43554264,  0.30757237],
       [ 0.15532807,  0.30922786,  0.26594141,  0.38746571,  0.48504596,
         0.49996281,  0.90177159,  0.97594083,  0.85914522,  0.6723971 ,
         0.62736416,  0.53057823,  0.54103773,  0.5976891 ,  0.62371223,
         0.6694755 ,  0.72141463,  0.70751034,  0.58449677,  0.44073082,
         0.47000454,  0.51013604,  0.43527454,  0.15484672],
       [ 0.04174452,  0.216109  ,  0.281491  ,  0.33576776,  0.36252585,
         0.5416965 ,  0.48327293,  1.11749579,  0.77210322,  0.6159181 ,
         0.48455809,  0.49067654,  0.46266418,  0.42061135,  0.3761251 ,
         0.33145048,  0.34339854,  0.6480376 ,  0.69294181,  0.59283091,
  

In [18]:
daily.Y

array([[[ 0.06310287,  0.15878103,  0.19869386, ...,  0.31777679,
          0.26324594,  0.1046233 ],
        [ 0.19219134,  0.18639497,  0.19945347, ...,  0.64150333,
          0.51833978,  0.47803707],
        [ 0.59840225,  0.38474171,  0.28108886, ...,  0.3825221 ,
          0.30140501,  0.43518631],
        ...,
        [ 0.27060958,  0.02433063, -0.14013545, ...,  0.2431566 ,
          0.23415747, -0.09412558],
        [-0.11191947, -0.1577069 , -0.10152955, ...,  0.64838448,
          0.43554264,  0.30757237],
        [ 0.15532807,  0.30922786,  0.26594141, ...,  0.51013604,
          0.43527454,  0.15484672]],

       [[ 0.19219134,  0.18639497,  0.19945347, ...,  0.64150333,
          0.51833978,  0.47803707],
        [ 0.59840225,  0.38474171,  0.28108886, ...,  0.3825221 ,
          0.30140501,  0.43518631],
        [ 0.34053808,  0.31329399,  0.28546777, ...,  0.50901897,
          0.55252208,  0.48885029],
        ...,
        [-0.11191947, -0.1577069 , -0.10152955, ...,  

In [19]:
period=PeriodDataset()

Data build range: [window(1977-12-01 00:00:00) - 1979-12-01 00:00:00, 2017-12-01 00:00:00]


In [20]:
period.X.shape

(39, 2, 12)

In [21]:
period.X

array([[[4.1, 4.2, 3.6, 3.3, 3.4, 5. , 4.7, 5.4, 4.9, 4.1, 4.2, 3.8],
        [4.1, 3.3, 3.2, 3.1, 3.4, 4.9, 4.9, 4.6, 4.6, 4. , 3.8, 3.7]],

       [[4.1, 3.3, 3.2, 3.1, 3.4, 4.9, 4.9, 4.6, 4.6, 4. , 3.8, 3.7],
        [3.9, 3.5, 3.5, 2.9, 3. , 4.3, 4.3, 4.7, 3.8, 4.1, 3.6, 3.4]],

       [[3.9, 3.5, 3.5, 2.9, 3. , 4.3, 4.3, 4.7, 3.8, 4.1, 3.6, 3.4],
        [3.8, 3.7, 3.6, 3.5, 3.6, 4.2, 4.8, 5.1, 4.7, 4.6, 4. , 3.7]],

       [[3.8, 3.7, 3.6, 3.5, 3.6, 4.2, 4.8, 5.1, 4.7, 4.6, 4. , 3.7],
        [4.4, 3.9, 4.2, 4. , 4.1, 5.4, 5.3, 5.5, 5.2, 4.8, 5. , 4.4]],

       [[4.4, 3.9, 4.2, 4. , 4.1, 5.4, 5.3, 5.5, 5.2, 4.8, 5. , 4.4],
        [4.8, 4.7, 4.4, 4.5, 4.4, 5.4, 5.3, 5.6, 5.3, 5. , 5. , 4.6]],

       [[4.8, 4.7, 4.4, 4.5, 4.4, 5.4, 5.3, 5.6, 5.3, 5. , 5. , 4.6],
        [5.6, 5.5, 5.5, 5.4, 5.1, 5.8, 6.1, 5.8, 5.3, 5. , 4.6, 4.4]],

       [[5.6, 5.5, 5.5, 5.4, 5.1, 5.8, 6.1, 5.8, 5.3, 5. , 4.6, 4.4],
        [5. , 4.4, 4.2, 4.1, 4.3, 4.6, 5. , 4.9, 4.9, 4.4, 4. , 4. ]],

      

In [22]:
period.Y

array([[[4.1, 3.3, 3.2, 3.1, 3.4, 4.9, 4.9, 4.6, 4.6, 4. , 3.8, 3.7],
        [3.9, 3.5, 3.5, 2.9, 3. , 4.3, 4.3, 4.7, 3.8, 4.1, 3.6, 3.4]],

       [[3.9, 3.5, 3.5, 2.9, 3. , 4.3, 4.3, 4.7, 3.8, 4.1, 3.6, 3.4],
        [3.8, 3.7, 3.6, 3.5, 3.6, 4.2, 4.8, 5.1, 4.7, 4.6, 4. , 3.7]],

       [[3.8, 3.7, 3.6, 3.5, 3.6, 4.2, 4.8, 5.1, 4.7, 4.6, 4. , 3.7],
        [4.4, 3.9, 4.2, 4. , 4.1, 5.4, 5.3, 5.5, 5.2, 4.8, 5. , 4.4]],

       [[4.4, 3.9, 4.2, 4. , 4.1, 5.4, 5.3, 5.5, 5.2, 4.8, 5. , 4.4],
        [4.8, 4.7, 4.4, 4.5, 4.4, 5.4, 5.3, 5.6, 5.3, 5. , 5. , 4.6]],

       [[4.8, 4.7, 4.4, 4.5, 4.4, 5.4, 5.3, 5.6, 5.3, 5. , 5. , 4.6],
        [5.6, 5.5, 5.5, 5.4, 5.1, 5.8, 6.1, 5.8, 5.3, 5. , 4.6, 4.4]],

       [[5.6, 5.5, 5.5, 5.4, 5.1, 5.8, 6.1, 5.8, 5.3, 5. , 4.6, 4.4],
        [5. , 4.4, 4.2, 4.1, 4.3, 4.6, 5. , 4.9, 4.9, 4.4, 4. , 4. ]],

       [[5. , 4.4, 4.2, 4.1, 4.3, 4.6, 5. , 4.9, 4.9, 4.4, 4. , 4. ],
        [4.2, 3.8, 3.7, 3.5, 3.6, 4.1, 4.6, 4.5, 4.1, 4. , 3.4, 3.6]],

      

In [28]:
x=torch.Tensor(period.X).unsqueeze(0)

In [30]:
xs=x.split(1,dim=1)

In [31]:
xs

(
 (0 ,0 ,.,.) = 
 
 Columns 0 to 8 
    4.1000  4.2000  3.6000  3.3000  3.4000  5.0000  4.7000  5.4000  4.9000
   4.1000  3.3000  3.2000  3.1000  3.4000  4.9000  4.9000  4.6000  4.6000
 
 Columns 9 to 11 
    4.1000  4.2000  3.8000
   4.0000  3.8000  3.7000
 [torch.FloatTensor of size 1x1x2x12], 
 (0 ,0 ,.,.) = 
 
 Columns 0 to 8 
    4.1000  3.3000  3.2000  3.1000  3.4000  4.9000  4.9000  4.6000  4.6000
   3.9000  3.5000  3.5000  2.9000  3.0000  4.3000  4.3000  4.7000  3.8000
 
 Columns 9 to 11 
    4.0000  3.8000  3.7000
   4.1000  3.6000  3.4000
 [torch.FloatTensor of size 1x1x2x12], 
 (0 ,0 ,.,.) = 
 
 Columns 0 to 8 
    3.9000  3.5000  3.5000  2.9000  3.0000  4.3000  4.3000  4.7000  3.8000
   3.8000  3.7000  3.6000  3.5000  3.6000  4.2000  4.8000  5.1000  4.7000
 
 Columns 9 to 11 
    4.1000  3.6000  3.4000
   4.6000  4.0000  3.7000
 [torch.FloatTensor of size 1x1x2x12], 
 (0 ,0 ,.,.) = 
 
 Columns 0 to 8 
    3.8000  3.7000  3.6000  3.5000  3.6000  4.2000  4.8000  5.1000  4.70

In [35]:
xs[0].squeeze(dim=1)


(0 ,.,.) = 

Columns 0 to 8 
   4.1000  4.2000  3.6000  3.3000  3.4000  5.0000  4.7000  5.4000  4.9000
  4.1000  3.3000  3.2000  3.1000  3.4000  4.9000  4.9000  4.6000  4.6000

Columns 9 to 11 
   4.1000  4.2000  3.8000
  4.0000  3.8000  3.7000
[torch.FloatTensor of size 1x2x12]

In [36]:
keep=[]
for i in range(10):
    keep += [i]

In [37]:
keep

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
torch.stack(xs[0], 1).squeeze(2)


(0 ,0 ,.,.) = 

Columns 0 to 8 
   4.1000  4.2000  3.6000  3.3000  3.4000  5.0000  4.7000  5.4000  4.9000
  4.1000  3.3000  3.2000  3.1000  3.4000  4.9000  4.9000  4.6000  4.6000

Columns 9 to 11 
   4.1000  4.2000  3.8000
  4.0000  3.8000  3.7000
[torch.FloatTensor of size 1x1x2x12]

In [48]:
tmp=torch.randn(64, 64)

In [49]:
tmp


-0.8340 -0.0333 -0.1632  ...  -1.0425 -0.0780 -0.1103
 0.1716  0.2069  0.9568  ...   0.0345 -0.1600 -0.5511
 0.4470  0.2974  1.4267  ...   0.4853 -1.3918  0.2542
          ...             ⋱             ...          
-0.9588  0.0827 -1.4392  ...   1.1038  0.1407  0.1535
 1.0873 -2.2632 -1.3709  ...  -1.1921 -0.0230  0.0217
-2.0188  0.8654  0.6202  ...   1.4177  0.2950  1.2091
[torch.FloatTensor of size 64x64]

In [50]:
torch.ones(64,14, 1)*tmp

RuntimeError: inconsistent tensor size, expected r_ [64 x 14 x 1], t [64 x 14 x 1] and src [64 x 64] to have the same number of elements, but got 896, 896 and 4096 elements respectively at /pytorch/torch/lib/TH/generic/THTensorMath.c:1036